# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Trail.create!(trail_forks_id: 64411, name: 'Cadillac River Runner', description: 'This is a cross country-style trail that also utilizes the bow river pathway to link up sections, and is best ridden at low water.', length: 3300, difficulty: 3, coded_path: "{mqvH`_kwT[kCJc@Eu@}@aD]a@KYUOYu@Uc@UUo@aE_AmDGo@i@uC_@yAg@aBe@uD_@}B[gAiBoEa@sAGa@JIvEoBBQQ}As@e@Sq@c@gAe@uBm@cAm@gBkBqDuB_Fn@uBa@uCBs@UiBkB`@LvAVl@BrAcBqAm@cAuAiEeCkHu@uDb@Us@qASw@I}@[`@WwC[qB]iDXoCMuALsDXiBdA\d@eBFkBb@aBdBgBjAgAvAiAv@a@vAkBVtAo@jBeA|Ao@zBo@tCDf@lBL")

Trail.create!(trail_forks_id: 156216, name: 'Regional Pathway - Edworthy to Inglewood', description: 'This section of the regional pathway connects Edworthy Park to Inglewood along the north side of the Bow River.', length: '13402.4', difficulty: 1, coded_path: 'ertvH`ovwTl@eAzIyIhB_BxC_DzEqEfB}AlBkBlBwBzBoCz@oA`AeCVoAtAyOJuAH{DPmBPeENq@AkBEaADgMTeCVcBFoAx@}EtAqHn@}Br@eEp@iE@m@RkBf@kCBWx@_CnAoF^mBnAgEtCgIvDeJfAwBt@oA|@_AZW~Aw@vC{@`Ae@r@m@p@}@~AoCRi@d@oCLe@Hm@@iCOkBEuCSaD[oAWcBEyA_A{FOq@WyBe@qAGWOcD?yTh@eQFqCByEC{CMeCCyHLqIFcA?e@QiBM][k@}BqDaAcBuAgB_@gAWuAmBkOASBSZmABW?q@W{Bm@wD[gAe@gAY_Ai@gAK[Uw@a@iCcAsDe@iA_DkGgCmFyFsKo@}AqCeFg@wAq@_DKu@MaB_@{GMeEBaEEU?k@\oNHoAt@cDbAgCt@sAtAaB\WtCyClAq@zA}An@c@JQPMLSPg@`@mCFm@AQ^gBFc@jByJXq@lCyN\oC`@yAVqAXyBTeAbAgD\sAr@eAXiARoBbA{E@QCW@[dAwHCaA@WH[LoAb@mCFk@NkDJuAZqCD{A?{KBaBFkAHk@JWFC\sBHeAPiAfBqH^qBNaBPeDNyEXqFHo@b@sB`@uE`@aDEm@Bk@`@kEB}BLi@tBqFXe@rA{AVu@\sAd@gATs@x@uEXwCHmC@m@KyAWaAmBeEOiAA}AE[y@e@g@Bi@LaFXg@LOLKyBdD]bEIb@IRg@PkC@cEOkASe@ESLg@A_@KQ_@UCM@K\{@TkADe@Ew@AkANyAToAz@cCHs@bAyCvBwF|A_DfBqCtBeBfAo@pC{@bBm@VDd@f@bAdBr@`AvC|B\HxFvLH@TOJQJIaAtNAh@QlBE@@aBIoA')


Trail.create!(trail_forks_id: 156458, name: 'Regional Pathway - Ogden to Inglewood', description: 'Paved pathway along the Bow River that access [L=https://www.trailforks.com/trails/pearce-estate/] Pearce Estate[/L] Park and Inglewood Bird Sanctuary, among other sites.', length: '7589.83', difficulty: 1, coded_path: '{ugvHd|zvT?OkA{CaAyBWCc@FyFpFy@n@_Al@gCbAq@RaDp@sBDiCOw@M{D_AUAOJMW_Bc@MXw@c@aEeAk@E_@GQQKEUQ_AUgB[}@GwDCoBl@mAr@}@|@_@P_@f@sEpICc@Qe@uCuCeA{@QIM?_@Ja@u@U@c@ZeAVk@Xg@b@o@Hg@VcBAg@Gq@Ju@IsAZ{CGmBH_A?yAQgJaD{D}A}D]cBEuMCm@Ow@EgFCmG@eDF_E^gA\OIqA_BOBGHC^yAhE_AdCIFCVsBfF_@_@WIUJq@dAE?y@}@MGcFFiCCcCs@WJg@Mg@[qAcAqAwA_AoAi@a@_BUmAc@wA`@Ih@c@Ng@z@gAf@iBdCo@ZOVg@lBkAfDk@zBYxBK|CE`@a@dAMd@Iz@Bf@?|@Xv@t@|EJ^j@h@nA~I|AdK\pADr@xD@b@j@Hx@ErB@LAvAG~BOdA[vD_@jCMl@Uf@qAhBu@^QVe@ZU|@Q~Co@hCOXK\SbCWhAm@bDQf@If@At@_@vC[`DeAlFw@jEm@pEI~@?f@HZr@pBFf@')


Trail.create!(trail_forks_id: 153372, name: 'Fort Calgary To Edworthy Park', description: 'This family-friendly paved path along the south side of the Bow River past downtown Calgary is part of the City of Calgary"s multi-use pathway system and is also a segment of The Great Trail (Sentier Transcanadien) network.   The east end of this segment starts at a pedestrian bridge at Fort Calgary on the south bank of the Bow River. Moving westward, the path passes south of Princes Island Park and then continues west parallel to Bow Trail.', length: '9269.45', difficulty: 1, coded_path: 'eupvHn}`wTe@?}@JMA[Nm@j@[j@Sp@[tAYzCYdAs@vB_BlG_@x@[XOp@O^q@`CAVo@xBsAhEw@zBDh@{BjGg@dAe@rBGn@oAdFQvCi@jBSjBGrBu@hEOvBMv@YdAWrBWhA_@rAQvAI`@q@fAWLuAfFKRKh@D^E`@oAtEkBjFa@~A]v@]~A?r@F\Er@Hz@@pBN`A@xBMbACzJNvH\`Gr@~IRfBfBnDdBfH|ApDn@lAhCxHT~BRrCrBlERChI~b@l@jB|@vAd@bBZfBZhEHn@Tn@BXC^UvA?jJi@rWMr@?rCDpCJlAEfDSbBAxDUtDG`FMbFRvEx@~CRfA`@l@d@T^\h@zC^~C?jBTvCJjB@xBItCo@nFArAq@zDMfAe@|B}@zDu@tCy@nC{BnGKd@_BbDQLU?}Aq@q@`@s@t@e@lAOj@Kr@aBlI[l@{C~GQt@u@l@k@|AkBbC]t@gB~AeAzDOzIaAzFYxEn@fEqBbLuAvLb@\Bf@Un@_D|W{BhLyDnKyC|HwBnCwAlCmB~Bm@pA}@pA{BbCgAtBy@r@c@dA')




Trail.create!(trail_forks_id: 151936, name: 'River Park to Fort Calgary', description: 'This is part of the City of Calgary"s multi-use pathway system. There are a couple of sections that are shared with cars on quieter residential streets, specifically: Riverdale Avenue SW, 1 block along 26 Ave. SW and the bridge on 25 Ave. SW. The north end of the pathway connects to the Riverwalk and Bow River pathways, providing access to the East Village and Inglewood.
', length: '8829.81', difficulty: 1, coded_path: '}fjvHjujwTaBgBk@kAe@MyErAoE\yBaAu@a@Ie@mAiAgEaUaEsVxBwXg@c@SECOTqA\{Cp@aDToC`@mIAiBy@cIm@iCe@uCW}Bq@}EU_AMw@_@iA_Ay@gAKu@Fw@Za@Vc@f@Yb@SRkApBU|@s@xEM`@G`AKd@Ct@UjBGTa@x@eAdBw@xAa@|@w@`AsArAQVShAa@b@OB_@ZcGfECrEGbAu@Rc@WaBSO?s@QYOu@Ie@Kq@Iq@_@e@a@a@SyBeEGSsAwCsBuJ_@mAM_A?iHB_EVwVMQPiNMk@]Kk@?{Ab@Dc@K}BWDoCz@_AD}GdCmAdAQ~@mAxDe@jGe@LgCoCgAmBy@yBa@}E?iFQeADoCJw@HUOa@JsAp@aAj@i@l@YNYNQhBiB\u@d@i@v@i@^i@n@_@z@gAt@oAl@cBz@oDjBwEZqAX_@l@]Za@j@VDPPCPuAfB}FLgBCkA?eBKkAiAkA_AoAw@Sg@g@yCmBcA]o@i@eADgD^_Dl@cCEc@w@mDc@}Am@Gg@a@k@g@uBmBeCiGuDkCoBeBiBmAoBMa@i@b@_AcA[iAu@cAoCsB{Ag@y@EUGIq@_@YaAc@o@{@oAmAmAfF')


Trail.create!(trail_forks_id: 130002, name: 'Regional Pathway - Nose Creek', description: 'This section of the regional multi-use pathway parallels Deerfoot Trail.', length: '11793.8', difficulty: 1, coded_path: 'kdqvHxo|vTkAFgATmA@}B~@aCb@cCp@uB^iC|@uAl@uCX_Cv@e@ZSv@IbBQn@s@\q@V_@D_BDyFn@u@h@_ASyAdAaAdAiI~FaAl@}B`Eu@^{Br@w@p@uBpAy@bB_CvCs@xAa@l@i@Z[IQ[aAmA[?_@NkHrBg@QkCr@_Bl@yAv@i@l@y@jA_A|@{A^g@Ts@Fc@Ec@F_@Z{@`A_@XYNe@N_AEO@WHQJmAxA[TyGxCkA~@iAnA[~@[r@s@d@}CfDSZ_AbGy@nEQn@OXwBxBe@\aAh@wB~CeArA_KpKkAdA_Ah@y@n@ORIRC^@vEUdDOX[NeDAOQIc@Gy@GYMWQMKAq@J}A~@{@RaAJg@Xg@`@_@He@?y@k@WW_A@YNQBSCQGYBm@ZWR]`@[n@aAzA{A`D_@j@s@h@IJiA`Cc@rAWf@W^s@fBMJmAh@W?w@Um@Bq@b@mBFg@NaAI_@B}@ZwQ`Aw@CYBSJSTOJ[D]?Yk@Sy@a@EQ@u@Nk@FYX[f@Ij@Dt@K^]HWCQGqAFgEnCaBOiA{@sH^s@KYg@q@RUd@mBhBmAZuCIoAm@iAuAm@{Bu@yBaAwAKaE_Ac@gB_@oDg@{AQs@NsBkBaJ`@mBl@yFU}Fc@}CeAiKsC}Ly@kDKcUC{DIuD@{CIwCBqCAgCVgD@qBTuA{@mBI}Fu@MCkDsAWAk@DsAVYLy@LQLqAnAc@RUBwC@eDCkAI[Bi@EqAHm@?iCH_BCc@B]AWFkAMUDaADo@Em@Iq@FaA?SGaCoC_@IQ@q@d@UV')

Trail.create!(trail_forks_id: 6350, name: 'ZC-DT', description: 'A sick trail we built last year with several different lines and hits.', length: '790.067', difficulty: 4, coded_path: 'al{vH|imwTVNLBPYp@o@lAj@h@w@JCl@PLCrAgBHET@JERODMJI`@BLGNA~@LBGFDb@BJDx@k@BGD@JAJMBSDK`@_@To@^q@n@[RGp@M`CHTHfCDb@A')

Trail.create!(trail_forks_id: 46429, name: 'Gerry"s Trail', description: 'A really sweet path', length: '1088.14', difficulty: 3, coded_path: '{e`wHlsrwTlB]XJXIN[`Am@tBi@tDq@jJcCb@Ld@Ep@]hA[b@UlCs@lAoAf@mAx@aGrAwBj@sBV_D')

Trail.create!(trail_forks_id: 46430, name: 'Gerry"s Extension', description: 'a good trail for when you cant get enough', length: '301.522', difficulty: 3, coded_path: '{t~vHvrqwTtBcBv@kAbAm@bAqAv@m@p@I\YL?LE')



Trail.create!(trail_forks_id: 16973, name: 'Sideshow Bob', description: 'Begins with a trail alongside the cliff-face of Bowmont park, then into a short tree section, onto the cliffs again, and finishes through trees to a pathway in the middle of Bowmont park. If you don"t like exposure, this is not the trail for you.', length: '1323.8', difficulty: 4, coded_path: 'utxvH`vxwTUd@e@Pg@HRf@V@LG\_@J?\Ih@JBNJNADg@FmAv@s@Po@h@E?c@l@Od@[ZId@_@|@SPKZMNI?MXYDEFCTUJCVQd@KDS^CJ_@l@g@fC?Jc@f@Oz@ORI\GJET?RIPBLCJYZOZGVML?JWMUDWbAMVC`@UFQ\G?[Ta@rCIlAQh@GFNXHXPRFXLNBLO@EHYtA}BpFWNk@FILYR')

  Trail.create!(trail_forks_id: 42899, name: 'Bowmont Singletrack', description: 'This is a route that follows some of the popular singletrack in Bowmont Park. Following the banks of the Bow River you will be treated to some decent undulating inner city dirt with a few short punchy climbs. This route can be linked up with [L=https://www.trailforks.com/trails/sideshow-bob/]Sideshow Bob[/L] directly to the SE and Twelve Mile Coulee to the NW via a couple km of new paved pathway and tunnels under Stoney Trail. Generally dries out fairly quickly after rain as it is exposed river bank. During winter it can be good fatbiking conditions, and very often rideable on a regular MTB with studs due to walkers and Chinooks. 

Be prepared to yield to dog walkers and oncoming bike traffic, especially on blind corners. 

There is one section near the Silver Springs ravine that does not allow bikes, stick to the upper track, signage is obvious.', length: '3763.32', difficulty: 3, coded_path: 'qf|vH~maxTRDFLLf@IfCBFP@PARYx@c@Tm@FYB_@DDBJJCl@y@Fs@@i@XwBAWUu@?c@l@wB\qC?MOgAIaB?s@P_AJqA?s@N_C@iADSPMPUj@i@ZG@UBGd@g@r@aADa@CWKQ_Ao@u@]OQKUG_A@W|@gAFS?WYoCKMc@U]e@CM?YHmAHSFCNBh@AVI`Ac@Xa@b@cAR]BO@q@Jw@CUOi@Fo@b@gAp@iAVq@Je@Tq@?[Ge@@g@Aa@DERCFEl@w@LYT}@^k@?KI@y@`@KL]n@y@`@GCAIBaAQi@Q]OMgBk@oAm@WQQUc@]Um@G_@Ae@Ds@BKNSVAFDNN@f@HZb@x@HJf@Rf@Zj@DHCV@NC`ACRFF?ZM^]Zg@Vq@FGl@QP?NCFGF[FKP?d@G`@JF?VKFGPq@l@c@HKXo@d@}AJITc@LK\IDKDk@Ni@Do@AOOo@?MDUPa@NQl@a@HKDOBk@BI|@{Ar@g@\g@XMVShB_CJIVe@JGLSHg@Ri@TOJO`@yATa@F_@NU\cAH[B[FMRUBM?]Zw@VmAZa@n@uAPQRa@`@g@Zs@P_ALWN?DEFo@JILm@B]To@')

  Trail.create!(trail_forks_id: 66336, name: 'CMBA Link', description: 'Built in 2016 by the Calgary Mountain Bike Alliance, this trail connects the Bowmont Single Track and [L=https://www.trailforks.com/trails/sideshow-bob/]Sideshow Bob[/L]. This is a reroute of existing trail, which can no longer be accessed due to a new storm water drainage system being built by the city.', length: '759.047', difficulty: 3, coded_path: '{wyvHl{zwTEh@Md@GLURUFq@F[GQMe@UGIQk@i@gC[i@MIo@IKEEBK^@JTJPPZl@T|@Z~@JbALj@DJHFLRJ`@JPBTYv@?TTPnAZR?RKJ??j@MhAEPa@r@WVELLv@VRFR')

  Trail.create!(trail_forks_id: 102817, name: 'Edgemont Ravine', description: 'Paved pathway', length: '3413.07', difficulty: 1, coded_path: 'ey`wHl_vwTHJJF`AVH?FDPf@@|ASx@IbAMNG@i@@_@Ce@Nu@h@]b@K`@CVQ^mAxA[V}@FYFk@h@KDILI\Yh@a@Xa@L[E_@Qm@OsAk@OOWg@]sAS[OKe@OuAcAq@]c@[c@K_@?k@Es@LWCYO_@o@Y[o@c@]i@Qg@k@{FGSa@gCc@oAUW_@OWEc@FOC{@a@c@k@oAaD?sBX}A@OCy@@iAB_@^yABUH_DLiCA_@PkE?w@Gu@EUa@{@Qm@Y_BAYBq@Hq@@sB\sBAk@S{A[gAy@qBy@yA_@mASqASwDa@mBYo@u@sAi@kACUAeAGk@_@}A_@qBWgBM{ACs@FwAH{@AKQU[QKMEQG}@DaAHq@T_ALw@@WASKm@_@y@Mk@GcFGwAQaBGaAAqBEk@Ke@Sk@{@oACIBQ')

  Trail.create!(trail_forks_id: 102824, name: 'Edgevalley Connector', description: '', length: '164.947', difficulty: 3, coded_path: 'mxawH~otwT@FMz@GdADfBA|BG`B')

  Trail.create!(trail_forks_id: 108617, name: 'South Ridge Extension', description: '', length: '204.875', difficulty: 3, coded_path: 'kc|vH|jqwTXWDAP[JmAXo@Vu@ZwARoAFy@H_@')

  Trail.create!(trail_forks_id: 8244, name: '12 Mile Coulee', description: 'The 12 Mile Coulee area is in the community of Tuscany, in Calgary"s NW.  There are trails on both sides of the creek that runs down the coulee, and there are many crossings, most without any kind of bridge.  For the most part it"s old school narrow XC singletrack.  Other than a couple of short and steep climbs, it"s not overly strenuous.  Be aware that close to 90% of trail users are walkers and runners, often with little kids or dogs in tow.  There are some sections of trail that have blind corners, so be prepared to dump speed and yield the trail.', length: '2865.96', difficulty: 4, coded_path: 'qj`wH`vgxTQ}@R{@H_A?QGY?qAHm@?[CsAD[^g@FAPOJEPSTq@Nq@XsBBCH?POn@y@FEl@Cz@BTCNIB?`At@NDj@M`@c@N]^UPGZV\BBD\?VW?IJe@z@mB\Il@Gf@AVCfALr@CTULSp@q@NGR?^LTCBEP?PF`AYJ@b@P\j@j@p@J@ZGf@k@ZPZHLFl@DNEN@JJv@j@f@CFCLKBGVcBFkAj@yBZa@J?TDn@UHIh@eBDi@BMTMHARKPC@ETEHGRYFQ\S\a@hAgBZQ`@w@Vy@VYN]NMLIRyAN_@NSPGLAJG`@kCLWZKXLLENHNLJBNEtAw@NCn@c@fAc@H@RQp@_@PQ^MRk@N?ZY@GNQJSLKHKNi@`@k@Nk@NCNJR\DL^RJ@JGJJBAPLn@pADRLZf@n@c@dAGXINGTgAx@c@`@eA|BSZ')

    Trail.create!(trail_forks_id: 33743, name: 'Tuscany Bluff', description: 'Dry trail away from the creek in 12 Mile Coulee. Good sightlines, but keep an eye out for dogs, as this trail gets close to the off-leash zones.', length: '2056.64', difficulty: 4, coded_path: 'yv_wHpxfxTQ[KaACG@g@CmCI]M{ASs@Gi@IWPBJJZJNAjABp@AhDJfAGPJV^p@H`@NP@TNt@fAv@t@FNDSAQVUXm@RYv@i@RIr@M|@BVa@n@BhACrBaBNSnA_AZa@FUd@oBF{@Lm@r@cAj@k@l@yAx@wAZu@T_AR[Na@h@i@hBuDXa@PIXGz@CX@zAXb@DDDd@BRDt@?NQHQJg@^mDJMLILAnBb@f@BdACvBe@z@D')
  
    Trail.create!(trail_forks_id: 100410, name: 'Lose Yourself', description: 'Part of the 12 Mile Couly area in the community of Tuscany, in Calgary"s NW.    This trail is South facing and runs East - West along the the old Bow River valley slopes similar to the Bowmont Singletrack.   The route follows the cliff side and has some  roller coasters on the west end of the trail.     Because the trail is South facing it tends to dry out earlier in the spring and is a little warmer in the fall.   Combining this trail with the [L=https://www.trailforks.com/trails/12-mile-coulee/] 12 mile coulee[/L] creates a nice out and back circuit after work or when you"re looking to fit in a quick single track ride.', length: '1092.58', difficulty: 4, coded_path: 'e||vH~hexT@G@HALAnAFj@B`DBv@Ll@GnBD`A?n@@r@Iz@Hf@Bt@MnBUxACjAGv@AlBHjBCxBCNYt@Id@EVClAEJMLADGpA@x@Ar@G|@QxAWvAc@h@[vAm@~DQv@UlBWfAGrAIh@KlA')

    Trail.create!(trail_forks_id: 3404, name: 'Burnt Forest', description: 'Loose rocks, technical uphill, river traverses and rocky downhill sections', length: '16091.5', difficulty: 5, coded_path: 'k{cnF_{x_DRxAWz@_@v@u@|Bk@~@[~@Y`@uDdJ[rAMpAQG_@RsAVo@VW?[VC?Y\@FOEUHQ\?ZUBCL_@JOLc@nBW^Tn@CdATbBZjA`@VNVFt@Td@[|APz@Bd@OxA?nAg@rF?n@Ux@[j@Qn@It@SXCd@W|@KHECKFOBQIS@WG?FOCOFMAQF[UIBw@c@a@KCKF[MKYs@OIO[N_@l@AjAWlAc@l@i@hA_CZeBAIa@WQe@q@^w@D_@_@[CUUq@MaAk@UA_Au@_@GwBgBQD[YUCGH_@]UAa@QSPc@OoAq@i@MK@u@Q}@k@c@Im@FKYBa@k@iCY@i@MaAzBkBhBYRiB~Bg@jAK^KzAo@~AAHThA@^UCMHFB?DAC[`Bi@fBI|AUx@k@l@IZ[Vw@VcAr@gAj@]F_Ah@YFuAv@YD_@Po@b@aAZe@FY@w@i@WGi@_@o@oAi@]Wm@M_Ai@q@uAq@eA]SCu@g@]E_@Os@Im@Us@Mw@s@c@mA_@B_@SM]Is@q@eAAk@o@eASs@_@_@]s@Gk@k@qA]aCWy@OQo@a@_AgBsCoCSI]@aAWsADc@f@]Nk@Iq@Wu@Fs@EkCFkBb@y@B_@FgAf@yAJoAV]Aw@c@e@EG@s@Xm@^]Hy@x@{Af@a@d@g@VgAfAcCf@aGRkBb@cBfAg@PgDlBy@p@w@Zo@LyAp@y@z@a@R_BhAMDa@EC@]h@WE_DGrB{D?E_@aAc@eBQYu@q@EKGoAXaCZsATgBNe@@iBTeBEK?wAVq@Me@Lc@Go@^aDJeC@cCV}@@mAe@eBEa@J]Fq@I_ASo@YsDOcAFk@ScAK_Ce@kC?OgAsFk@mBQmB[eAQYEm@Wg@WoAeAeDK}@@]TcADq@Ew@Pu@bCcD~@oBdB_Cz@{@t@Yv@aABY`@K~@eAHUAc@Pa@RM\NZMr@s@b@UHBjAkALARo@z@q@nB_DDBAEr@gANEx@o@z@y@PCf@W^GRBf@a@j@Iv@YZa@h@SB?tElF^r@l@fBr@|@~Bv@j@F~AHnAQpCeBpBy@b@Yh@y@j@}BDIhAyAv@wA^a@v@]bBa@n@IvCF`AQz@e@`@e@h@y@`@QPy@V]fBaE~BaEPH`@h@h@hBh@f@nA`@hETfAPh@?dGXvAYtA{@b@OdB_@xAE`@FbAf@pAG~BzA`@x@Ln@B`@GhADlB^zBCh@Hv@@dANnANlCW`AU^a@ZMZ?HFdANd@PfArAlDlEvFpA`E^n@pAn@p@BfBXdAh@n@Pv@Ap@HVPd@r@VlAFrDj@rBdAlBp@j@v@vBj@~DB|Aj@dBTd@VRPd@VxBf@hAp@vCf@y@bAwC`@F~@n@LDX\FXpBh@l@BNEnABrAShBIb@@h@Ov@e@p@Gf@RX\Zl@`@lADzAQlBBTFBH?rAu@jAc@jAq@LEVg@j@oDtBoEf@c@hAe@l@IhB|@nC~@VLFLy@n@c@f@sAp@i@`@_A|AYx@Mf@')

    Trail.create!(trail_forks_id: 3405, name: 'Pigi-Agios Charalampos', description: 'Mixed trail. Paved and loose dirt sections', length: '8704.77', difficulty: 4, coded_path: 'evcnF{pf`Dm@WGIOu@ICIFQWMEGT?IK?a@hAo@nAGRk@j@Ol@e@t@_Av@i@HWrBOVOD_@\_@f@UHM?UUe@IQHSTK\J`@C~@FXBf@GROBWGURg@vAI@QO]MUBEDKBIII?yD~@u@Cg@D}@f@wAj@]Rc@b@BBSDALkAj@?HKM[HkAnAIRg@\C?g@bDK?WRc@nAQtABrBRn@Ah@k@z@GAS|@c@bAw@v@SXMZWb@O`@wAbBq@T[Vo@p@O\SXeAdAMVSL{@fA[B_@MU?[VgAf@k@LiA@}@La@Nc@HmAO{@Bs@^QPmAM[I_Am@So@KSQAg@H_BDYNo@j@SViBxAI@iAOSBQH}AdAk@|@?HkAPo@TeA?SI}@?SBo@VI?O]SG]Ac@RS?SDW?ICYSQAYk@oAeAk@w@m@k@M]IIOIc@?SDQ?g@Oo@q@KCw@gAEMSOG?c@e@]OO]MIk@?kAY}AIc@Ng@HIHK?o@j@WDIRi@j@]h@IBi@rAUNWXeAfBaAt@ECwAbB]Ns@B_@NuAbAi@N{@t@If@KX}@\c@f@M?YHSRYDMHe@BWH_@Vg@DsBdAQDYPu@Nq@Xs@F[?]MW?YMi@g@mCHkAj@IN?\KVg@?MCIROAQXIDI?c@z@CLq@p@AXJd@FHC\MREf@I@NxAPPJl@PRNDHPj@b@j@RPB|ASL?\QRB\MPAjAJbAEPBTR?`AH`@`@Ct@WTAd@a@hD_Bf@QXHZEDBJ?\SbAG@ERDLIL?JKZ@XST_@ZMFBf@Wb@I|@]t@k@b@Ff@tAZ\\HRLnApA|Ad@XNL?j@JZj@XTn@RbAp@h@PXDTNPAb@^Z`@?LDCZLP?LHl@HVMZDPLHLPIvAh@pAAjANXR\?tAa@VAVHVRdATdAOn@W^{ANoAHwAj@aDHeADyA?mADA\\PDd@Eh@MdBMTIb@?HPJ?Fq@Gk@FI\`@NJj@PRJRBVEFWO_ABUNHBRHCl@cAC_@OiAB{@Kw@B_APYX}AdAqAL_AJYZGRIp@?TKp@JLAJG|@FJGVBv@M?BRoAz@cBH}ANKJ?')
  
    Trail.create!(trail_forks_id: 3408, name: 'Agia Marina-Kormi', description: 'Uphill double track and rocky downhill single track', length: '6408.6', difficulty: 4, coded_path: 'uugmFobfaDP?PDFAl@SFOZETJR?XXN@`@K`@Wp@RTAPU?K\St@Qv@g@\IPM^?FIB?tA|@jBj@PVl@IVFhAM`A@rAj@KPAhAZz@?^XlBNPAHXHDLXVb@NBNZ`@Ll@Bl@DB?XZZLl@z@z@Nj@^j@^`Af@\?^QpAITYVk@H[Qs@Ie@k@k@MaB^VTsADyBr@]B]]gAc@IKI[A}AQ_A}@{A_@UUCgAAiC|@WDoA@g@^c@x@KF@HE?cBuBk@kB_@y@{@oCa@[_@e@e@?IKHKASPYJi@ESMAW]Ks@NoDZaBDk@Kk@II]AoALg@RICUe@w@iA[wAy@sBUMI@eA`@O?sAW[Q]y@c@s@OMg@G_@NEAU_AIEaAQqEqCmAnBy@`BEBqAGWVCFYHkAfBUp@c@d@gAyAM?URQA[q@WS[EEBB@ABQCOU]M]COHe@AyBb@e@h@E?Ub@EM@FIXMTSHMIQw@Sa@De@Se@KIUHCYYKw@@o@NmAJaA[e@@MHWGYDqAbBgBv@GFe@|@e@l@]Jy@OI@g@LMXaCJyAp@}@rAQzAg@fAa@?q@Sc@@a@Wa@@a@IEH}@Zi@`@e@PqA~@u@jAMl@w@|@{A\g@XIJW~@m@xEa@|@aAzAmApDMzBJd@^l@CRCDMDu@AyAO{A_@c@@gBZUWQu@Ys@}BiA_BsAeA[G?oCmA')

    Trail.create!(trail_forks_id: 16459, name: 'Fuzzy Groover', description: '', length: '534.445', difficulty: 4, coded_path: 'mgyuHl|rwTk@o@[gAM?KCSHc@r@{@dBs@nBmAT{@Hw@PSf@WpBGPSF]d@Oj@a@PUHQVWLw@t@')

    Trail.create!(trail_forks_id: 16511, name: 'Votier"s Flats Riverside', description: 'Green singletrack has a few roots and rocks, but nothing major. Connects Votier"s Flats and Bridge 7.', length: '1055.11', difficulty: 3, coded_path: 'ka{uHbrkwT^kAFa@TUd@\ZyA@k@B]Xy@Jc@DG?Sr@MFQ@SEQGEj@SHIVDt@KDEd@iC@aABm@?_BCq@Sc@Ta@Ac@W{@o@iAQBOUOAe@i@YNGEUm@DO?MQEGE?Sa@KMcASE[mBUw@Ye@Rk@XgBTk@H]A[WgBAU_A{B')

    
      Trail.create!(trail_forks_id: 46436, name: 'Regional Pathway - Edgemont to Brisebois', description: 'Part of the paved multi-use pathway on Nose Hill', length: '4371.83', difficulty: 1, coded_path: 'wo`wHdsrwT~B`AnBl@b@EvCoJTmDlBa@p@_@dAaAhDsApCg@hAgAvDgFjDsFdAYpB]fBi@nDEfASrCDn@K|@e@r@Sx@MhA@dCVtDNXIPSt@kAx@cClA_FpAcJNsBAyTrC}BbBgA`Ag@z@s@pAoBpC_DrBeDt@m@~@U`AMlCUd@OjC_Bh@a@XChAq@VA^RF`@?f@KdAqAtDU\wAbAOXgAtASl@Cr@NP`@Nj@Dh@TlAjAl@|@jAzDBh@Ch`@CbAQ\OjCQvB_@tD')
    
      Trail.create!(trail_forks_id: 92948, name: 'NIMBY', description: 'An alternative to the main Edgemont route that rolls along between backyards, and the top of the escarpment slopes.', length: '2473.53', difficulty: 3, coded_path: 'gu_wHpbswTKVCTcAtCNPh@LdAC`@G`@U`@M`@?~@e@VCRIJLVHf@InAEt@Uv@O\?TLLp@A~AJh@^Nf@IjALr@VdAfA~@jA|@v@dB@`@FjBLjAT\\r@hAJh@DfAe@x@?^Oj@mAhC]f@a@X_B@a@GsAD}AIeADWPq@hAOf@EtA_@d@kB`@mBLq@@o@F]AYBi@Ni@Z{@jAOf@W|B?rAFj@Nh@Nx@RtADjBKbBEXWpAc@rAKl@@bAH^HTj@fA^f@p@n@d@XfAdA`@zBAD')
    
      Trail.create!(trail_forks_id: 103502, name: 'Surfing on a Web', description: '', length: '941.46', difficulty: 4, coded_path: '{e|vHdhqwTs@qBq@_BUw@_@mBIkA]_Da@iCCa@?qAQ{C@sAO{AY}AOk@s@qA_@i@c@_AKa@{@_A_@m@]{@Y}@UkAKyA?{@Ge@MgE?_C')
    
      Trail.create!(trail_forks_id: 103338, name: 'Eastern Front', description: '', length: '283.142', difficulty: 3, coded_path: '_v|vH~{kwTf@NN?FEXEXK\E^@`APPHXDRH\BRHRRJVVZVPh@J')
    
      Trail.create!(trail_forks_id: 103322, name: 'Borderclimb', description: '', length: '829.299', difficulty: 4, coded_path: 'cc}vHdciwTVNFNDPCTGPYZ}@lAa@ZaANOLS^Mz@BL\`@D\LfBAjABxABHQ|BClASfCBBCH@hACz@QbANx@f@VHLFr@TbAr@tBD`@LVn@|Bj@rC')
    
      Trail.create!(trail_forks_id: 46439, name: 'Regional Pathway - Huntington Hills Tunnel', description: '', length: '1021.49', difficulty: 1, coded_path: 'u~_wHd}kwTOiBQm@s@eBAa@JuAQsBE{@b@yDAu@Mi@_A}BWOIkA?cAGe@}AcBOg@OgAEqAOaCAkAKwAq@}CEiCC_ODMGsB')
    
      Trail.create!(trail_forks_id: 103811, name: 'MacEwan Uplands', description: '', length: '1055.83', difficulty: 4, coded_path: 'mlawHtyowTAbAN|@XpCPV\LPRh@bA^hAl@~@L\b@bFn@fDh@|Bt@zERzCXl@Lh@RtARjCLp@Vl@fAbDj@jCL^V\\\^n@Tp@LfAFlA@zA')
    

  Trail.create!(trail_forks_id: 46504, name: 'Plateau', description: '', length: '2339.25', difficulty: 3, coded_path: 'i|_wHtbqwTXNh@Q|A_A|Aw@pA{@d@c@v@{B|F_O`CsHpC_IZq@HwCd@yGVyBXaIDoBTuC|A{[\}Bn@sHDeUFm@^_ALiBrAwD\uANiBj@_DTgCAwBDc@FC')

  Trail.create!(trail_forks_id: 46483, name: 'Long North Road', description: '', length: '1775.68', difficulty: 3, coded_path: 'mp}vHltowTcAO{DCk]JmNJkDGsAKq@FcIEkG?sAF_EDyASoEC')

  Trail.create!(trail_forks_id: 104298, name: 'Slauson"s Extension', description: '', length: '527.671', difficulty: 3, coded_path: '}z|vHjylwTYEa@UQc@GIMe@[aCUc@_@i@O[UYMUEWA_@DaAGYW]SOOC[WWg@[cA_@y@Y_@a@a@YSu@w@a@YSUYK')

  Trail.create!(trail_forks_id: 103675, name: 'Tableland', description: '', length: '421.705', difficulty: 3, coded_path: 'ss~vHnjjwTR|Ab@pAd@bBXlB|@tKXpEd@`C')

  Trail.create!(trail_forks_id: 46436, name: 'Regional Pathway - Edgemont to Brisebois', description: 'Part of the paved multi-use pathway on Nose Hill', length: '4371.83', difficulty: 1, coded_path: 'wo`wHdsrwT~B`AnBl@b@EvCoJTmDlBa@p@_@dAaAhDsApCg@hAgAvDgFjDsFdAYpB]fBi@nDEfASrCDn@K|@e@r@Sx@MhA@dCVtDNXIPSt@kAx@cClA_FpAcJNsBAyTrC}BbBgA`Ag@z@s@pAoBpC_DrBeDt@m@~@U`AMlCUd@OjC_Bh@a@XChAq@VA^RF`@?f@KdAqAtDU\wAbAOXgAtASl@Cr@NP`@Nj@Dh@TlAjAl@|@jAzDBh@Ch`@CbAQ\OjCQvB_@tD')

  Trail.create!(trail_forks_id: 92948, name: 'NIMBY', description: 'An alternative to the main Edgemont route that rolls along between backyards, and the top of the escarpment slopes.', length: '2473.53', difficulty: 3, coded_path: 'gu_wHpbswTKVCTcAtCNPh@LdAC`@G`@U`@M`@?~@e@VCRIJLVHf@InAEt@Uv@O\?TLLp@A~AJh@^Nf@IjALr@VdAfA~@jA|@v@dB@`@FjBLjAT\\r@hAJh@DfAe@x@?^Oj@mAhC]f@a@X_B@a@GsAD}AIeADWPq@hAOf@EtA_@d@kB`@mBLq@@o@F]AYBi@Ni@Z{@jAOf@W|B?rAFj@Nh@Nx@RtADjBKbBEXWpAc@rAKl@@bAH^HTj@fA^f@p@n@d@XfAdA`@zBAD')

  Trail.create!(trail_forks_id: 46441, name: 'MacEwan DH', description: '', length: '1310.87', difficulty: 4, coded_path: 'qr`wH|krwTg@uA{@oB}AmBwAqBSB[|@QAGQC[GYYQy@IiBCOQIc@LoA?[Kc@CgAYc@a@SUQOWMGM]U[UuAAmAKmADmCKc@@kCEcBGo@Mg@Go@Fw@TgBGe@[Sc@_@{@gBa@oBHoAN{@CsA@s@Dq@Js@@m@d@mD')

  Trail.create!(trail_forks_id: 103282, name: 'Middle Bypass', description: '', length: '1050.99', difficulty: 3, coded_path: 'yq}vHjwlwTJXLv@\rDD`HDd@B~@IbCAdEFxBIxA@r@CRCzC@hBBp@GtADt@CvALzCAz@Eh@ArBE~@B|@A~@KpBJzBBlFCFExB')

 
  Trail.create!(trail_forks_id: 104634, name: 'Brenner Grind Extension', description: '', length: '744.283', difficulty: 3, coded_path: 'gf~vHdfqwT]Qe@{@M]O_AIO[a@KIm@Wy@eBKIa@M{@g@e@MSk@mAeFwAyEOs@Ew@]oDU{AYkACu@Is@q@qC')

  Trail.create!(trail_forks_id: 46536, name: 'Bypass', description: 'Awesome beginner singletrack with a fantastic view of the city, Ride this.
Have you ridden this yet?
Yes?
Good, Go back and do it again', length: '1124.94', difficulty: 3, coded_path: 'cw}vH~eqwTb@mAjByHh@yDIi@zDiFnDgCb@s@D_@AeCFgCVoCTmAIgCH[fAiBfAuAj@WjDyCz@kAR{@`@cD')

  Trail.create!(trail_forks_id: 46514, name: 'South Ridge', description: '', length: '929.547', difficulty: 4, coded_path: 'y}{vHp{pwTh@_D`BwFLeCCoCBeAKcFEcEMcFAcNBwDCcB@wAHyBJ_Ab@gC')

  Trail.create!(trail_forks_id: 103278, name: 'Middle Earth', description: '', length: '490.438', difficulty: 3, coded_path: 'yy|vHtimwTRGVBXA\HN?\IF@lAx@JZ^tB^dA^j@f@^b@p@NDNEhAo@f@MPKj@k@^Kj@e@D?BB^B')

  Trail.create!(trail_forks_id: 103335, name: 'Mixed Pattern', description: '', length: '435.097', difficulty: 3, coded_path: 'u|{vH~zkwTNFxANdAd@h@`@Rf@\dB^bDLj@\\f@\H@bAzAVJrApADJ')

  Trail.create!(trail_forks_id: 103819, name: 'Saddletown', description: '', length: '468.479', difficulty: 3, coded_path: 'iw|vHj{kwT}@G_CAm@Tk@Lk@`@}Ax@[RYXc@h@Uh@o@j@YS}@u@i@mASK]@')

  Trail.create!(trail_forks_id: 103319, name: 'Short North Road', description: '', length: '641.987', difficulty: 3, coded_path: '}o}vHzdmwTuPDkQI')

  Trail.create!(trail_forks_id: 24389, name: 'Green Tea', description: 'An easy and simple trail for beginners. It has small rollers and jumps to keep your little ones progressing', length: '1722.03', difficulty: 3, coded_path: 'kyvvHpxcxTU~@IbB[ZGBO?GCW]Mk@Gm@Q{@a@}@Oo@GMIIg@KMq@IWQMCDEbBE@OIEsAOUIVC`A@xAOpAOFDbBMBO_BCgADqAOmDg@SQWCoBQAIh@@vAFx@Ef@k@jA]xAQxCO[?y@Oe@Dm@SFMn@GJIMGu@Qc@][IUKg@KsAM[EA{@Z]\KbBIV?TK\E`@INKi@Bq@Cu@WwASoBKgBMa@QUK[SmAq@kBGcBEKWVG@GNIGS_@')



  Trail.create!(trail_forks_id: 153491, name: 'Regional Pathway - Fish Creek to Glenmore Reservoir', description: 'A family-friendly paved path within the Rotary-Mattamy Greenway is part of the City of Calgary"s multi-use pathway system. The north end of this segment connects to the loop around the entire Glenmore reservoir.   The south end of this trail is 130 ave. where the next segment of paved pathway continues to Fish Creek Provincial Park.  The highest elevation point near midpoint of this pathway is the new (2018) pedestrian bridge crossing Anderson Road.', length: '6326.67', difficulty: 1, coded_path: 'cl{uHleswT[Ow@NCHAx@FdHCjBI^a@h@cAv@QHk@JkAZq@HKDo@@gARuAH}AZ]JeAL}@RU?m@GaB`@yABo@HqA?_AEqH?g@C{@?e@OmBc@c@Wa@MMA}@Y}@m@i@WOM]K]QGAa@DUAcAUUWcA}@uBmA[g@qBiFsB}E[iAU}BYaJ@eALyBCmEKLB|@?pBCPGB[BcAEGCCGH{@F{COJI`@MzBEpDBrCAtBM`GCP_AvCw@jB]lAYnAGdAOd@u@^{@`ASPc@PqCv@u@Xm@\y@|@g@ZkCpA_DrA[He@@s@Ag@FyB@}AKc@ReEd@iBHuB@WI_Aq@k@][ISEoC@yBO]I{@[}@m@y@[OCm@?YCwBj@ID]f@gAp@s@NwALk@@sBIk@@_ALqC?gAIaBE{B@oAHaC@c@AmEHuAHgAPg@BwA?}HNQEEKE[E_A@eCCoBAyICa@I[IEa@CgAWmCg@_@Ky@m@sA{AKCe@LICQOe@u@QO[E]g@a@a@uAw@s@i@WI[_@')

    Trail.create!(trail_forks_id: 145804, name: 'Regional Pathway - Weaselhead to Glenmore Landing', description: 'Paved path along the south shore of Glenmore Reservoir.   West side of this segment allows access to the Weaselhead, the east side is behind the Glenmore Landing shopping center.', length: '3506.03', difficulty: 1, coded_path: 'e_dvHbdswTIDCUBKIBHSToA^_AhBwC~@eCdBqGz@cEzAuF~AqFrAsCx@wDZeAbCaLVaARm@^w@b@g@b@u@l@m@Zc@l@Ut@m@NUZeAjB{INuA@i@G_@GKYQ]EMEm@w@UUYEc@USAs@Ni@^_@P_@OO]GGM@KHGLMB]GMUIEi@EMGi@u@QQICcAAgAc@mAU_@AqAXIAGEEOFc@Vs@PeAJkBFyCAc@Ku@A[DqAEeAMu@MuA?o@Jq@Pc@dAu@v@y@~@e@Xc@Pu@Ly@h@_B\q@f@u@Tg@FWVe@VgAPc@\OLK\}AZy@`AsBtAiF\aBDqB@_DAu@b@iK?gEEmEC[sAyAQe@CCEB')
  
    Trail.create!(trail_forks_id: 145803, name: 'Regional Pathway - North Glenmore Park to Weaselhead', description: 'Family friendly paved path through the Weaselhead nature area connecting [L=https://www.trailforks.com/trails/north-glenmore-park/] North Glenmore park[/L] to the south side of the reservoir with connections further south all the way to Fish Creek Park.', length: '4050.94', difficulty: 1, coded_path: 'oyfvHnotwTNEAGE?KFMVe@tAMbAOjC@`CEvC@nBVtERt@FHH@VOHOv@wC`@q@f@[lAWd@GpA?ZEz@?TBh@Vt@j@nAt@RXpDpItAxDl@jB\t@zEzOn@rCJx@@X?v@[bD@~@LXLj@nBhM`@`APdA^`DVrC^lA`@j@`AbA?IDIZc@HYBc@M_BBcCKmA@k@I]AQ?w@Hg@RKRSPYHW?SIq@@cAPeCHo@FmBJk@LqA?WJ]PQXAf@IHINa@T{A^sARi@N{@Ru@NcAF{@Lu@`@oANiAHWtAuCPm@p@kBr@eCZq@n@eABUrA_EDa@rAwDlA_Ff@mDA{@Ei@]wBAWh@aEHcCZkAl@cEHqABqCRqGf@oD\}C')
  
    Trail.create!(trail_forks_id: 145801, name: 'Regional Pathway - River Park to Glenmore', description: 'Family friendly paved trail.  This is a segment of the nationwide The Great Trail network (TransCanada Trail).   Connects River Park / Sandy Beach city park to north end of Glenmore reservoir and loop around the reservoir.', length: '3833.31', difficulty: 1, coded_path: '}fjvHjujwTN?FIf@eBLYNIVEd@Dh@GRKf@i@`@w@b@k@v@o@ZOTEZ?r@WXDVR^h@XV\h@P^Lx@PZ^xAXb@^|A?HEHQBCDLd@?l@G\MR[XUbAKVeAr@ALBr@AfDLFl@Hp@bA\RTAb@Fp@?`Ab@RP`@j@n@p@p@d@r@r@b@h@f@V^f@BLHtAQx@Iz@PdCIlACfBBHJBNBx@Bn@VxBhBtBxDj@lAl@j@Zf@HRPj@@\IhACzAJfCFl@@lAC~@DZNVJJf@NdE?\@HBFFBJ@X?`BGpIFn@BDj@FpA?vAFnAARBPJ^f@bB~C@NKlAQ~@oAzIC^@JDE^wCDINBnAf@AODaAH}@H]D@B^MzBVoCNoCp@wF\oBDeBDm@pBwNN}@\uAV{A~@}Dj@yBbA}C')
  
    Trail.create!(trail_forks_id: 151936, name: 'River Park to Fort Calgary', description: 'This is part of the City of Calgary"s multi-use pathway system. There are a couple of sections that are shared with cars on quieter residential streets, specifically: Riverdale Avenue SW, 1 block along 26 Ave. SW and the bridge on 25 Ave. SW. The north end of the pathway connects to the Riverwalk and Bow River pathways, providing access to the East Village and Inglewood.
  
  Parts of this pathway are cleared of snow in the winter, usually from Sandy Beach to 4 St. SW.
  
  Watch for pathway closures by the Stampede grounds during Stampede. The closures are typically well-signed, but you may be detoured temporarily onto streets.
  
  This segment is a segment of The Great Trail (Sentier Transcanadien) network.   This goes past the famous Calgary Stampede rodeo grounds and to the pedestrian bridge at historical Fort Calgary at the intersection of Bow and Elbow rivers.   This bridge is at the point of a  3-way ("T") intersection on The Great Trail... the Great Trail goes both east and west from this point.', length: '8829.81', difficulty: 1, coded_path: '}fjvHjujwTaBgBk@kAe@MyErAoE\yBaAu@a@Ie@mAiAgEaUaEsVxBwXg@c@SECOTqA\{Cp@aDToC`@mIAiBy@cIm@iCe@uCW}Bq@}EU_AMw@_@iA_Ay@gAKu@Fw@Za@Vc@f@Yb@SRkApBU|@s@xEM`@G`AKd@Ct@UjBGTa@x@eAdBw@xAa@|@w@`AsArAQVShAa@b@OB_@ZcGfECrEGbAu@Rc@WaBSO?s@QYOu@Ie@Kq@Iq@_@e@a@a@SyBeEGSsAwCsBuJ_@mAM_A?iHB_EVwVMQPiNMk@]Kk@?{Ab@Dc@K}BWDoCz@_AD}GdCmAdAQ~@mAxDe@jGe@LgCoCgAmBy@yBa@}E?iFQeADoCJw@HUOa@JsAp@aAj@i@l@YNYNQhBiB\u@d@i@v@i@^i@n@_@z@gAt@oAl@cBz@oDjBwEZqAX_@l@]Za@j@VDPPCPuAfB}FLgBCkA?eBKkAiAkA_AoAw@Sg@g@yCmBcA]o@i@eADgD^_Dl@cCEc@w@mDc@}Am@Gg@a@k@g@uBmBeCiGuDkCoBeBiBmAoBMa@i@b@_AcA[iAu@cAoCsB{Ag@y@EUGIq@_@YaAc@o@{@oAmAmAfF')
  
    Trail.create!(trail_forks_id: 156472, name: 'Western Headworks Canal Pathway', description: 'The [L=https://www.trailforks.com/trails/western-headworks-canal-pathway/] Western Headworks Canal Pathway[/L] follows an irrigation between Chestermere Lake and the Bow River. The section north of 50 Ave. in Calgary is very rough and not recommended.', length: '24030.2', difficulty: 1, coded_path: '_|kvH`bwuTXz@t@~J|Cj_@tAn\D|AL`@bBvC`BlAZhBf@FPO\@pB~AXDz@GdCvAVHzFfDlObHrLxF|@x@\FvBp@p@VpH|Hh@v@hNrc@tAlDvAtBtCpCvIxF`SxGlYlJfDbA`IxIlBxA`Ah@dDdGd@|ADlA|Ct|BDzBPvB`Ttr@t@`BdXhZx@l@v@vAbd@|f@n@jAjDfRDvAgDpa@UdBsDlc@@vCb@jDvI|YRvABjPDt@tIlm@tPzc@vK|Vr@x@tG|Er@Zp@bAnBlNHhBQzAuB~Hs@vCoAfHe@vDc@~FmCtw@{Bzr@U|BuArJcApDkA|BuBnDuBtBwR`P{WtTgCbBiF~ByEj@y@AeF\_B\cCFsCLc@We@_Aw@lA_HwNqBcCyAuAaBiA{UeJaJ{CmBu@cCUwCHeEpA}B|AyCvDmBlE}AdHaA`B[TuGlB_DtBe@^oIlSmBnEw@hC[zA]zBIjBWtKoAtp@IpBa@jB_@rAKbAqAVwAn@{@BkJ_C_OkEqBRY?}@e@qGGyDr@{GfByABcHaAcKaBkCcAkD_CuIeHiR}QoEgF{FsI}CwFwByEaCsAcFoB{EqBcE}A}CoAsD@iCb@gCbBwBzB}DdFqBjDcDfFmA^')
  
    Trail.create!(trail_forks_id: 143835, name: 'Bow River (east side) - Queensland to Higgins Park', description: 'Paved bike path great for families and children.   A pedestrian bridge over the Bow river at each end of this leg allows you to travel the trail network on either side of the river in either direction as you chose.', length: '3766.62', difficulty: 1, coded_path: '}k|uHrwzvTDNWo@y@_BOQGASLe@nAi@hAW^o@d@m@@SEU@SFm@h@K^?r@q@rB{@dBk@t@i@~@{@dAq@lASh@gArAWd@sAhAk@p@OFQI[YSIm@@IBwBfDkBdCiEfHSPQD[AUBg@G{@c@uAYy@Ug@_@[Kg@EwAD{@CIHEPIpBELGFIFo@DQFq@LOCQQWC_@UWA]j@g@tASVSJQAgBF_BXcALsBFyAHu@?o@Fw@Ji@ZODS?{@a@QCI@m@NyEp@aATu@?[Jm@Hy@d@{@Vk@TaALk@p@SLKBq@Ag@WUE{@CkAOeADu@L_@?u@P]Di@Nk@`AOPaAh@_@JMBe@CuAHYA{@FsATm@Fg@?m@N[Ni@d@ULUXUJQN}D`C_A`AmAb@y@b@EFUz@@XR`@t@hC')
  
    Trail.create!(trail_forks_id: 27842, name: 'Sunset Meadow', description: 'The name for this trail comes from the golden light you"ll experience in the fall as you ride through the tall grass near sunset. There isn"t anything particularly technical about this trail, but the slopes onto and off of the meadow are a little on the steep side.', length: '1225.13', difficulty: 3, coded_path: 'y~yuH`dpwT]Rm@Vs@Py@H_B^OEYYWGo@Zi@Fe@PaB`B_A|Aa@lB_@tBQd@o@bCk@hBEn@RdDJh@TXx@xAv@lAl@h@j@^fANVJ`BX|BEl@[l@OHgAzAKZJj@HZBZC')
  
    Trail.create!(trail_forks_id: 98173, name: 'Shannon Terrace - Bebo Grove', description: '', length: '2075.16', difficulty: 1, coded_path: 'gnzuHl{rwT`AiAFy@Lw@PY^GhAa@`@i@|@Sb@F`AONW`@qADW?k@Z}@Xk@dBaB\_A|@u@\c@n@kBp@k@Aw@IgBLa@@c@E_@Ua@a@kAyAy@eDuBc@g@?iDEUS[SSOk@GI_@Q[WQ[Wq@CYFqAF[Ck@Kg@EeB@SNm@NQt@SZELGTCRD\CZDXCTB\Lj@\VBJEPWFQFo@D}AWeBYu@Ig@SwCFsA?e@SeC?uAGuBMa@Yi@[aAaAyBWSq@Ui@Ie@W')
  
    Trail.create!(trail_forks_id: 98172, name: '130 Ave. - Everglade Circle', description: 'Paved pathway with access to Bridge 1.', length: '2136.88', difficulty: 1, coded_path: 'cl{uHjeswTKt@GxFHhAPfAJ\N\LRz@z@ZJRBxA?hANL?^]LLl@^PDVCX[NC^JLEN]FYF{@R_BRq@fB{BP]N{@DkAFi@Xu@z@eEXw@RWNEv@@pBoA`@ERFXl@^zARzAFvAHfAJjDBTHHb@HpAH^^f@j@TAd@z@^Lv@iBXQ^j@bAVd@Yf@MLe@Fy@Gs@Nk@TK\_@p@ARO^K^FRJPMPUPaBRgA`@_Ax@y@Do@VQXK\Q\J\EFmA`@c@\_B')
  
    Trail.create!(trail_forks_id: 98732, name: 'Marshall Springs Pond Trail', description: 'Wide gravel path around the Marshall Springs stormwater ponds', length: '1641.62', difficulty: 2, coded_path: 'suxuHfsnwTK[Ke@IsAi@q@Ie@KQ}@}@SM_@LOTKf@E`@MTg@Rg@DYEUOG[Ck@?cASyB]{Bs@}CwCyEiBoAs@o@c@gAMi@o@qA[]Wo@AgADYPCTMT]H[nAkA~@EdBHj@V`Ap@f@d@PRJd@`@j@rBzDv@lB@jAWhDL~CNfDHj@TfA`@|@')
  
    Trail.create!(trail_forks_id: 27924, name: 'Canyonero', description: '', length: '1225.13', difficulty: 4, coded_path: 'cq{uHftmwTRZZx@\b@Tb@NPVIPARER@XEXQTKVANBf@@NBZUNQRIZIdAiB|@iAR]ZOf@o@TATFTEPBXCPBJG')
  
    Trail.create!(trail_forks_id: 27864, name: 'Western Marshall', description: 'Sweet singletrack in the trees...', length: '597.717', difficulty: 4, coded_path: 'uzxuHfinwTC`BUzAe@`Eq@rDWdAEXLd@Sp@]|Ae@v@mAhAqAz@j@bF`@hBd@X')
  
    Trail.create!(trail_forks_id: 27902, name: 'Pipeline', description: 'Singletrack link between [L=https://www.trailforks.com/trails/shawnee/] Shawnee[/L] and the bottom of Plunger.', length: '572.676', difficulty: 4, coded_path: 'qbzuHzqiwTk@pBGd@Dj@Cv@s@rC{@xCa@\a@Hk@^kAxAe@rAw@rAOdCl@x@UjCZp@')
  
    Trail.create!(trail_forks_id: 27830, name: 'Cabin Trail', description: 'Connector trail from [L=https://www.trailforks.com/trails/bluff-to-flat/] Bluff to Flat[/L] to the gravel pathway. Before the storm water pond system was built, there used to be the remnants of a cabin on the site where you could practice wheelie drops.', length: '188.103', difficulty: 3, coded_path: 'aezuHdtlwTmA^kDg@uAF')
  
    Trail.create!(trail_forks_id: 100020, name: 'Macleod - Bow Valley Ranche', description: 'Paved pathway.', length: '4301.37', difficulty: 1, coded_path: 'g_zuHz}ewTGs@BmBDk@d@uA\qBn@_AjD{DR]h@sD@cAJa@d@q@`@c@XMT@b@QfA}@pAuBPOd@Gd@ONWjAcDh@gA`AkAzAYf@OXq@Tu@b@uDRqBZcC\}ACu@[qCCm@BiB`@cCf@aCXkAd@cCRUXShBk@~@a@~@]`@i@L_@?}ADaAl@uGtAwGpAeFb@sAf@aAbA{AlAyAjAWbAGnABnA?`AEdAI|@a@l@c@h@u@tAyCRyAEc@_@_CEm@Bc@Fa@p@wBh@oAdBsBNWl@WrB}CrDcD~@o@NU`@aAR_@|@k@l@g@b@i@jAuCXyA\cCJaAx@mLl@}Jj@cI@oAQeDGuBWwBcCwP')
  
    Trail.create!(trail_forks_id: 164021, name: 'Regional Pathway - Douglasdale and McKenzie', description: 'This is the paved regional pathway on the East side of the Bow River, linking Douglasdale and McKenzie Towne.', length: '5169.75', difficulty: 1, coded_path: 'cyvuHhwxvT`BuAj@s@lDoD\a@\w@Ju@@k@Hc@TQPFH?Oc@LBPJQaAGOVc@q@s@aASwAw@mAkAuBeC_BmCsA}C{BkDqDmFcAgD{AeC_Ac@}A`@gBw@uAcBmAO_A{@iA_@e@c@gAuAgAs@u@}AmAoAu@q@w@_@wEgAoCJoAM{AWy@@oAf@s@Ii@Oy@\_@D{@{@iAi@UAaCd@y@d@[d@]JM?[g@OE[LoA?c@Fy@\eCv@SN{@Ti@FkAZeA`@_An@c@h@c@dAk@r@QJS@KIa@m@UE}@v@y@bAa@z@a@j@w@d@[HYXw@^u@l@o@X_AVWDq@Dw@hA}@z@g@hBKbAkAxCc@rA}@~Ck@tAS~AeBdGa@bAGh@Mf@[^]lAq@z@M`@GnAcAbESzAQPQdEmBvCCXDb@TnAKbASx@cC~GOPuA~@[r@GTGpAg@t@eBdD]f@Mf@?t@Fl@Z`A`@fC@^Ab@Q`@oAtBSb@')


    Trail.create!(trail_forks_id: 46069, name: 'Sheep River Road', description: 'Sheep River Road is also known as Hwy 546 or Township Road 194A / 195A. It allows access to Sandy McNabb Campground, Bluerock Wildland and Sheep River Provincial Park.', length: '46674.2', difficulty: 7, coded_path: '_ghtHvaoxT?bpAIpAuIpN{@jD_@~GUtb@TrF`AbHxAxEfBzD`C|Cx@z@dMfHzHdGpBnD`CxHdArIhAxq@z@zl@^vD~BzKfJ~ZnSxd@pEjJhCdInBnKt@bNUtkCb@rFlA|H~ApEjEdIlD`GtCtChFrBlLpApJdEnHjHzEnHrL`VbBrFfLpo@tHddAdA`G~EbStGfUhAfJhB`aBUtN_@bFiBvMwF|Q{Zft@eApLAfOLtGt@dInD`OxAx^WbDkAxHOr@@rMiBxPA~EfCpWSv@FnFk@vBLv@S~BLfDzD`RVtGl@tCn@lAdAfAdMbFjBxCpKn\N~E@|HwKvi@oCj\HfASpAc@z@qC~RGxElCnZRhTi@rMo@rZ_Cb^}AhTeCtTeEzOiDvJ?~B|AfNGpBInFqCfJiNdP{RpKeUxQcAtBm@fJrBx`@gBjQErB@fAzH|^hCjJhAvDNjDFtJ[fDkBvF{@rDGpCt@la@ZdCxFjQ^pAHdBSrBe@rBWlCg@`EI`ELjFz@nKFdC[bDiCzIErBZhEzHnr@EzDcBpR^zI?hPHlEl@bFf@bDhG~TvHxm@?tEm@lND`Bf@~BzAdElA`BdC`MbEzGtBjFbB~M|Uzn@nNlYhCxPZdIiApLeA~a@l@|Fx@lE`BtCjUtU`KtChGnHxA|CbJrO`QpRtK|JvC`GfF|LxE|HnBpAjFrBtFbH`FvBhAtAf@lC`AhIlQ|Q`AdC@lGVtAfBrDz@pGdCzD|@|Cp@dEb@jBdCdEf@xLOdCwCvOGlANvBhBvDfKzO|CbUVrK\fAj@xA`B`BvBlGDfJVzBu@zIZpJNbADdC}C~INvDlAtJLhTpE|Sr@lArH~Tl@zDVjDf@jDpArDt@vFR~ExA~GjDzIxApE?dGwAzI?dBRpAjApCt@dCt@lGG~Id@`G~BjJ^pCu@xHqBvZs@nDcAzMAzBF|CAnBwAbJ]tCwB|Fc@lCq@lL_@|CyBfHaB~KcD~ESjB]|FWjBqDdKFrBTtA@bHUtE}Cp_@G`M]lEkDhTiAfF[nFt@nR@pR[dIcBjH]vBHlE\nDFlEc@lTLhE`B|L')

    Trail.create!(trail_forks_id: 17748, name: 'Death Valley- Windy Point', description: '', length: '14049.7', difficulty: 3, coded_path: 'usatHh{_zTQCWSe@RsAa@sA`@g@DONYIa@e@QGg@DgAZO@kAc@c@GmA{@OcAc@q@UG_@]YKGKe@Ak@IeBcAs@CmAH{@My@RI\UAMGC@S^UL]B}A]a@?}@gBkAe@cABo@l@k@fAm@`Bi@NaCs@c@BaAa@iA?wBn@yAhCo@l@?Pe@LYRq@BMPuAp@KVYnAUFwBCwBtBGb@BBUZm@^Ud@QLYDe@p@{@l@g@Dc@NQh@UHqApAULk@DiAv@g@BULY?_AU{@FiB?eAdAqCnFoB~AYh@cAG{@NeAnAgCjEcAQYa@YQoFNmAWYk@{@_@i@VQfDuArBi@vB}AvBwBnAi@f@wAs@kA{D{@mH{@OYPIjAHzEIh@cAhAYxCa@r@a@dCs@pBYfBWQgBb@{@`@INWF}AYqAJeAMkBc@eBTe@Ge@F_BfC_@?iAo@gAoA[{@mCNkBOi@Hy@Yc@F{@fAcAb@aBh@gAdAs@JuDXuA@y@]w@HWVWj@k@d@wBf@qC~AqBNgAIu@Xi@IkArBwBKgBr@mAHa@NuAzBu@?YSo@b@sCd@_@Xu@rBsAn@Af@YJq@xB{@t@wBD[b@g@pA?hA_AxBg@PQr@GMOV`@XFlAr@NtAlAh@GjDiCr@QlBoAr@SbAD`@Gj@a@zCk@tBG`@YtAX@Hr@StBZpClBlAXh@WtAoB~ByAbDMfBrAbAtA`CrJh@bE`@lAbAbArCNdBb@z@pAh@nEr@~AHrA?~AV|AvApCVfFGNP`Cx@r@j@APXp@pFHlAVrAbDxFh@pCj@jEX^z@tCh@FpCxClAj@z@nArApAt@lAz@`@tBbEb@ZGFFr@p@x@vEvAr@p@NWz@]|AYj@L`DO|Au@nBa@vBaClAi@j@?fCYPX?OfB}@FSvCkBlAOZc@`GcB`A@z@o@fBYPs@h@i@tAYhC}AvB`@fCGtAk@z@?r@i@z@GxCVdAj@p@IXYb@q@rAcAtAIfIcHlBoAHUjB{Aj@[b@c@r@YVW|Ay@~Aq@pDyBhB_AtAcAjAg@`GsGb@u@n@k@b@o@fBkBFSFCr@{Ar@oB^wCHmA?cDYkGa@cDYgD?aCj@iCjAqDp@{@')
  
    Trail.create!(trail_forks_id: 45910, name: 'Gorge Creek Road', description: 'Gorge Creek Road is a seasonal access road linking Maclean Creek Road and Sheep River Road.', length: '21334.9', difficulty: 1, coded_path: 'g~btH|qvzTw@?_@z@TdIn@dMt@hGEjHe@nFuHtP{InMTlLu@pJ[~I{@`GoGxUiEpC}DbD_FQqAr@uGvIeHdB{HfJgCXwBjHiMdPy@vCm@xAuA|AeCl@aABmA]uEgDgFyBaBa@}DZyM`@aAGsDTcFe@gDsAiDoAgCaCkMqFcDkCqBo@sBmByAqDqEsEuB_@wAHgB]sAc@mE}EoA[yBn@_C?{@o@}H?yAQsIeGeCs@cBw@}Ce@_Bs@m@qAcDuNmDuG}EQ_Co@{IyH{JcJoBoJc@e@g@Qk@r@s@jDqAxCuDfAsBvDsA~@m@?c@mAiAoF_BsBkBgAy@oBmEgH?_E_CaGe@sDkDeE_D}LsAoDyA{@s@iCqG}A}@i@u@_CcBeKk@eByAgAu@iEMqCd@mGiB_HOwFl@cL_@}AjA_CEmAe@kDUoUjAoJo@eB`CmLfDeI?}ADsDqAiCU_CH}AcEyJcGwF[oBgCmAcFlAcE?gBh@kBF_HaGqIyCuGqG{H_F_GePmE{Ko@mLgC{DaAGk@qCfBeX[oF?yJNoFuAuLgCwFsDs@}CcA}EoBuAmEoHsKOcHsDwBcEqCqKs@mDwBgEi@u@bAwBvBkBa@aDG{AGgBbDsGPoHeBaDmENiCjBgJd@aK`AiCTwIjB{@pBoFrDsDH}A{@}AToB?qC{@iCqC}AuAeB{Ah@aAF{@oB_@yGaCmE?aAp@mBoBcGyAkHgEwMwFsJ}CyCkCKw@m@k@mAW}Ay@sIm@sRLaCd@oBGa@f@uDDoGs@cHqBoIkCoIiC_M')
  
#Trail.create!(trail_forks_id: 46611, name: 'Gorge Creek Trail - South', description: 'The southern stretch of the [L=https://www.trailforks.com/trails/gorge-creek-loop/]Gorge Creek Loop[/L], from the Gorge Creek Day Use Area to the Threepoint junction. Not good if it has been wet.', length: '9661.44', difficulty: 4, coded_path: 'softHtl_{TxBBt@RvA~An@bFrC|EzFjEhAnBl@dB@dA[bBEhAp@hD`BdHw@vASpAJjBEtBBbB~@jEv@~@`@Nn@fEt@bEdAbDj@jC~AhBpCpBbAhBfCjDCnDxAbFfArARlCL`CAdCfAfGh@nECfFBzBGnFt@vHZjHw@dBaAhFc@hFm@bEeAbDQlFoAtFaAxAa@lEn@bGvDlCy@`DqAvFMzGmEfIiA~BM`CRxDkAzL}@jI]h@BzHoDnC{CfFi@jAq@vK}AvN{@pBCbEm@|EApF_AxGeBtJsBlKuA~Ha@rCy@vEiG~NqBfGwD~HuBbAqFtDaHbDoDz@kC|BaJ`MeAjCaEdDeBhGcIxDoEdDaCjB}B~C]z@wEdAmLxB_Gi@_F_@mBwAkB_@yAf@q@M}@ZwAjBuDpIeDtAoBt@}A\')
  


    Trail.create!(trail_forks_id: 141559, name: 'Old Forgetmenot', description: 'A great connector from Threepoint Canyon over to the Big Elbow Trail. Great views up the south pitch of Forgetmenot Mountain. Mix of narrow doubletrack down low,  and tight singletrack on Forgetmenot mountain.', length: '17534', difficulty: 4, coded_path: 'qeytHjdb{T`BfQxEnFdIzKbR~HrDf@bGnTTl[lBtIvD`GtA~M`CrOxF~EdQlh@fDvRxFvJjAjDT|DaCbAaAQaDqGoGyCyFp@gLO_@pGvCfJ{IOcGNmIfF{C|HkClEqJhC`AtAzIQdJgBlDbHmDdLaBdMcDbH}MzR_AlEUpVcE~LJnFjBbAbEcAvB`@vLnBzDxGxEnMzKdIfKbH|LnMlFtAxEs@|NNxEfBeF`GzIs@lEp]bCtP~@lPnF~P`DnFjAbOxEbPdJvIbFhKvAzKtAzCbElMIbHwC|L}JfBwDvBeHlEkCdI}MfXcFpGyFjDgM~FmDdAmEeAsK[kEl@w@dB{JjKoG~FmFa@yEhCaMfUzArDwBlEkLjI_HfEH`NuAvJTdIyG`N')
  
    Trail.create!(trail_forks_id: 94965, name: 'Big Elbow', description: 'The section of trail between the trailhead and the [L=https://www.trailforks.com/trails/big-elbow/] Big Elbow[/L] campground is an easier track, while the next section is mixed terrain that can be steep in sections.
  This trail is part of loop starting at [L=https://www.trailforks.com/trails/little-elbow/] Little Elbow[/L] Trailhead going (clockwise) to [L=https://www.trailforks.com/trails/big-elbow/] Big Elbow[/L], Tombstone, Mount Romulus. The Elbow Loop route typically starts on [L=https://www.trailforks.com/trails/little-elbow/] Little Elbow[/L], proceeding counter clockwise to [L=https://www.trailforks.com/trails/big-elbow/] Big Elbow[/L].', length: '20969', difficulty: 3, coded_path: 'kd_uHph`|TRk@PW\}CJa@@MCYUu@IKMII?SRG?IMY{@_@u@]oA[i@d@aBHIVg@l@u@ZUh@KT?NG|@OV?ZFdAZrAh@hDM\DJAfAH`ABTDdBATBnBKXDt@A~@DPFjAFXETOHOt@c@ZKP?TGd@GDGLCJKFAPQTGHKJGJBf@Md@_@b@Or@e@RIp@}@VOXEVIJBRA`@MXHJGLAR@NFb@@|ARp@A`ANb@Kn@C\@bASJEh@c@l@WFGf@DhACp@HL?l@RbBv@dAZdAb@b@Zj@TzA\N@TA`@Nl@Bn@N^DHAJD\GH@d@EJ@ZAd@KFB^GN@VEd@ALETATDLET?z@WHGRAt@[RCz@YFGj@Kv@[h@IrAKd@SP@PIR?^GZKLQFU\{CPaANm@t@aCVgA`@_CNoCR}@`AcBp@_AlA{@z@s@tBcAPOt@_@h@SPA\IdBk@xAq@x@W|@c@jBg@NIp@Uv@_@nAa@TOpAa@nAi@p@Ol@[pBw@nA]VQd@UtAi@`@SXI\U|B{@XQTIv@Mb@SjAOnBg@j@Kf@Qv@OdBUj@JtALt@PXAXF`@AND\f@XAHCRc@X]ZOFBP@j@NFAXSVGj@GHMPKTk@TYBHf@DXJj@r@pAtAt@p@pAf@^Tf@Tz@p@VNd@BRCVBf@?vBQz@@fAHRJVFl@TZ^LXLd@b@|@l@r@h@\JJn@J^GP@\K\APHh@Jf@T`@FXLnBl@^H`@Bz@G\@z@OFGV?ZEnADNBVLt@HfB`@v@Lz@\n@t@~@|AZb@^v@`@p@N`@`@l@t@zAr@t@|@pARRF@XAHHL^h@t@Lb@d@p@LHPT@VG`AKr@M\CRKTi@f@HbBDXN\Rr@R`@Tx@^|@fAjB`AtAt@zAxBzDdA~BrCjFd@t@r@~@PFh@\XFRHP?^Jb@@hAPFA`@Nl@Hp@^PTl@`@Jb@LFJPF^r@p@NZbAdAt@SL?l@ZHP`@d@h@`@f@Db@`@PDb@?NGLAHGH?TD^NH?RI^WTC`@SV?^YxAi@NCd@FdA\ZNNBh@Cx@Uf@EN@l@LfBt@RNlAZTAhAYTAzI|C`HZ`CxBpF`DbACl@c@bH|CfGb@zDrDdNdBbBn@fEbErAbEvA_@tABvBbFfAjDbAr@jAJnCpA~BjBtBp@rAhAlBjCtChCxCbCfCl@r@vAjBdCxArDvCjMS|EzAnDuBdCzA|LzAdRhA~Oq@fOrDvFv@vB\tCTxJPdE?`Bp@bBQ~KLnDhD~VjAbFrAhDZlEjBzIUxCA`CNd@T\bAKH\L`ALrDx@vFj@rCRrCjA`FbCxE`ChDfCzB~AlB`DxFdFdRrFtLzBjErC~B`Cb@r@rBd@bAz@tAp@bBd@|Ar@hBtApApCnD\zBd@nBbB`CxBjFzAvJ]zCJbGGjDVlCx@xEFzCn@xAm@pC[bH~@lGGnDHhEr@xCzB`DrA~EwAtIa@tDs@lEDhBVfAC~Au@~JNpAVnA\d@^|BC`A{@rFAf@OXi@zCMfAIRAf@e@pAKjAK\GdBWlBArD~AtItZ|b@xDpEvArBxHt\RbRd@Sv@qHbD{J')
  
    Trail.create!(trail_forks_id: 139681, name: 'Kananaskis Fire Lookout', description: 'Access road to Kananaskis fire lookout. Fire road on east side (gravel) of lookout is still in use and well maintained. West side is not in use anymore and has short vegetation growing on it, no gravel, just dirt. Still sees maintenance once in a while, because it is still part of the winter x-country ski trail system. Prefered direction is from east to west. Best downhill is the west segment.', length: '5551.8', difficulty: 4, coded_path: 'gd_tHv}h}Tr@?r@SRCb@DJFf@x@n@~APNXDx@BLDN?p@Vr@Nd@@lBIz@@`@Ar@WhBeAPGNBFDFHDVCj@ITKNc@\MNGP@VJJd@PXPJNP`@^`C?h@Eh@?x@FjAPbBJTV^h@`@LBdACh@ETIx@g@PE`@SXSNQVMXI`@SXDJGAQKOOM]QY[WKKKWIu@}@CUFWXJn@F`@CPGNMp@Qr@[R?hAQpBc@^DnA\bCVrA@d@EfAA\Jt@b@l@Jz@Gp@Kj@Dp@Rp@^XHPJ`@HbADRANKZId@[R]Z{@HKJAHLJAV`@p@f@JD~@HXC|@Yd@KLIN?n@Lh@Vl@LX?^Ef@Od@?`@GXFh@^L?f@Mj@EXBl@Rv@Fj@Cl@@TEl@At@F^Mf@CLG^?pAm@Nq@b@s@H?tAq@J?nA\^D\G^MjACv@L\@JFTB?Hc@n@MZETIJGh@B\Rv@?NH\LRN~@JXF^Xr@bAv@\Dz@l@PTTn@f@l@v@d@xAf@HNNJVf@f@p@N?x@Xx@DJB^`@Xd@JHZJBIR@PNDHl@Jd@LVLj@BLCXNd@FHJJBZBNATIBD[h@Op@GF?f@JJVBb@UZUJCl@a@PGJDFF?~BHj@Tr@RTJx@DDAFDTXb@Vp@Jn@Dt@?h@Wh@UVy@l@Wh@Y^gAv@e@j@KVWz@INGd@aAtD]bB{@fCy@|De@xAk@zBYhCCb@@VWtCO~@G~BIh@_@fEKj@AXT~@HL')
  
    Trail.create!(trail_forks_id: 77736, name: 'High Rockies - Canyon to Boulton', description: 'HRT from Canyon Creek Campground to Boulton Creek Campground', length: '6941.17', difficulty: 3, coded_path: '{ejtHlks}Tj@Vh@IlAdCv@NjAJdBElBZ|A?xAXpA[|@DbAYx@a@~@Tz@?t@H|@Gv@BdD`@|@Ev@Dz@Pv@Hz@E|@Jz@BxBZtBIlBZ|@?jD^|@Y`A{A`@u@vAcET_@TUr@WTON[HCDKr@QR@VJ^B^Ob@e@fBc@hB{@HKVLNg@PIXArAbAVANOj@wAHm@?{@JIXAPDNCJODQQaFJs@Zq@ZgA?ITa@T}@JOn@Wp@MP^X`@dBrAXHDHZZxAl@`Af@d@^J?PH^x@fApANJJRTDj@Sr@m@|BmEfAyAv@i@ZSZFlA?HEDOj@{@Zw@vEuCTGnBPPENg@?SD[Gw@Fw@NQTCHpAFJT|AEr@KNe@dC?n@T~@Zd@v@TjA?p@NT?|@m@rAe@pAOtAEXD^WZY\EbCmA`@e@Xq@l@qCNO`@OHOT}@\ONODKNQNIZa@d@SVa@zDyEJUfAmF^cAJk@T[fAa@Zk@H@b@WTa@X_@Vw@Hq@DaAE}@O_@As@PwAvAiElAsCf@iBxAkANk@NUNAZDJJN^NbAl@tApAlD`@XZJj@?PEd@aA?ONO^HxAp@f@ZlAf@XAl@LNLlADp@?`@EX@PBTPrBGZO`@_@TMT@`AThAPd@AbBf@`Aq@Zj@NJl@Rj@l@BTZf@l@`@d@N`@RZJT^Nh@PNRHPf@Td@TIf@k@XQTa@VIXDPH^b@v@BVHHJHD?BrA^v@XN@FD?DHJHDv@Uf@k@')
  
    Trail.create!(trail_forks_id: 5930, name: 'Powderface Ridge', description: 'This trail can be ridden in both directions.  I prefer riding North to South, parking at the start of the Powderface Trail (where hwy66 turns to a gravel road at the intersection with Little Elbow Campground).   Ride up the Powderface Trail to the intersection of the Powderface Creek Trail.  The wide and sometimes loose single track climb is 100% rideable if you have the legs  As the forest opens you"ll reach the intersection with the Powderface Ridge trail.  Turn right and re-enter the forest for some somewhat easier climbing until you come out on the ridge.  The ridge features several short sections of technical rocky riding where balance and power is rewarded.  At the very top of the ridge look for the marker for the trail as it descends sharply to your left back into the forested slopes.  It"s a long and fast trip down with a couple of short climbs to wake up your tired legs.  The last few hundred metres of the trail have suffered from years of erosion and have become a braided mash of roots and loose rock.', length: '6776.85', difficulty: 5, coded_path: 'axjuHdhb|T`@iAXKp@iCz@]LkAMiALcA?mAU_AY{GPyRNuAOkBTS`BNz@GNo@Gi@GsBz@wD`@o@Fo@GyAPcA`@o@XwBh@gECs@d@cFdAcAQoFPk@zDcAz@aCbAcA~AwBfJ_CXY~@]bAs@_AuAlE}Ci@c@X{@fC{@r@a@`@s@~BcA~EOxCFj@GbEgBHs@XgA`@YfCd@|Bv@NOf@M?e@pEMtAmB~@cB`@aB`B{@pAz@hCn@|CaC`@OfBmATw@Fs@h@a@nB]zBw@f@yANcAj@w@tAmAd@S`@k@n@KtCJhB\j@XlA~@vBnDVr@TbAn@HbAIlC`@~@GT]Je@j@_AbAiAxAoBTi@bAs@rBr@fBz@p@?T`@~@bAn@?~BT~@s@v@Cj@HFNr@d@h@b@jBl@\OXk@bCFv@HxDYbAFd@Kz@JlEFtAHXNh@?~Aj@XINWz@F`@\XJr@?bAn@f@Gl@Cf@JfABTLXd@X?N]d@B\Tv@J`C?tA\p@d@j@HjA\r@FTO`@?LV`@P`@Uf@K')
  
    Trail.create!(trail_forks_id: 5934, name: 'Elbow Valley', description: '[L=https://www.trailforks.com/trails/elbow-valley/]Elbow Valley [/L] [EV], along with [L=https://www.trailforks.com/trails/sulphur-springs/]Sulphur Springs[/L], has been used by mountain bikers since the late 80s. It is an old hiking trail that also gets used by trail runners, horses and cows.
  
  Most people start EV from Station Flats, and use it to connect with [L=https://www.trailforks.com/trails/sulphur-springs/]Sulphur Springs[/L]. East to west on EV past the SS turnoff puts you onto a looong climb followed by a loose descent, more climbing, crossing Moose Mountain Road and then a fairly long descent that will cross [L=https://www.trailforks.com/trails/sulphur-springs/]Sulphur Springs[/L] and continue down to meet Family Guy and then cross Ing"s Mine Road. The trail climbs for 1km past Ing"s, and then gradually descends the last 2km to Powderface. Note: the 1.1km west of Ing"s Mine Road is shared with the Ushoulda downhill trail. There"s a decent chance that if you"re climbing up, somebody is flying down.
  
  The trail surface varies a lot over its length, but the east end has seen the most use and is seriously blown out in places. Overall it"s a blue trail, but some parts may have you thinking it"s much harder. Expect everything from narrow dirt singletrack to scree to what looks like a steep gravel road with big root steps across it. Like [L=https://www.trailforks.com/trails/sulphur-springs/]Sulphur Springs[/L], EV has turned into a connector trail, allowing riders to construct loops with other trails.', length: '9416.43', difficulty: 4, coded_path: 'ayruHdtb{TbDnF~BrBdCnBz@`BJ~@?~CXtAfBp@rA?xAj@Hz@MbAb@r@zBCvBe@l@Jv@K\YhCYz@h@X`CbA?nBp@bAr@~Ar@bAzBjDrFz@X`DLrDfAPTPnBNr@FdBG`BOjBNrBGlC?UGz@QXUh@G`AYfCFjB\r@Hz@?~@Iv@i@bAs@dCcAxA{@dBgBfBcArDs@dBYXWdAYd@]Nc@dAa@bC?v@n@dCQNS\g@xAHvBh@hCFpAb@l@d@~CCvBFxAXhCY|Ah@r@dArHFtEX~AFfA\K\c@r@j@\`@PbAJPtAFnB{@jAqA~AqBlBgBhC}ATuAd@o@Pm@X`@l@rDL\h@Bz@i@hAsBRNC`AKp@BbDfAtCHfAYhC{@vBl@bDn@tCtAl@tAa@z@r@r@~B`Bb@bAl@PhAF|Av@tCd@xApAlC`@hBGhA?\{@hC?lBFtAj@vBs@vBYnBPj@h@Yr@uAr@PFN?r@s@vBFFb@OFN{@xCgBdAmBh@c@j@fBp@`@KFXXzBGXz@v@h@Ub@?rAkA~A{@h@k@j@ClBqAb@z@p@r@H`@?lAc@bAWlAQ~Ba@z@F|AYzCa@pCa@dBFr@Op@QnBXpCFtCgCjBYzDI`Gi@xC?zGz@fFr@jHFlA?tAXz@QfCdAhCFh@GzCuAzKXhEz@nDVdBHpCNh@dAlHF|Ar@tAFXQbAHz@h@X`@jDH~BYz@UXa@FCTNJj@T\`@\jDxA`CdB~Hj@~Al@rBj@fAhC`G')
  
    Trail.create!(trail_forks_id: 98881, name: 'Iron Springs', description: 'XC SKI TRAIL - SUMMER USE ONLY
  
  This is not a good trail, with at least a couple of huge swamps along it down by [L=https://www.trailforks.com/trails/snagmore/] Snagmore[/L] and Elbow. It"s better in the north, by [L=https://www.trailforks.com/trails/sundog-loop/] Sundog Loop[/L] and [L=https://www.trailforks.com/trails/boundary-ridge/] Boundary Ridge[/L]. Use it in case of mechanicals, injuries, etc. when the singletrack is too challenging.', length: '4551.53', difficulty: 1, coded_path: 'y{{uHhr~zTXe@lA{@d@w@NkAEqABWHExA?J@ZTTBrB{@jAo@f@S^C~A@t@C`C_@d@P\^p@tBXXVJj@Oj@e@NUh@yApByDlBuBp@}Bd@k@jA_@fGyAt@m@bCyBjCgCfA}@rBmAtDoBt@s@f@w@XwDZsAp@oA~@eAp@}@bA_A~@cBd@_Ad@iANmAT{@B{@R_ATOFW?i@Ia@e@{Aw@kA]_@iAg@_@]i@w@e@oAQqAC{DUmC]gGBc@T_@p@HdCpD|BdF`ApChCzJrAtEtAfDfA`Bd@h@ZVRt@CXFNETH\U|@Nb@NLJTpBO\WVEJOb@GdBw@z@W\Qz@g@b@g@j@YHgAGq@Ws@e@y@@UUwBEq@@q@NmAn@iBp@kAp@}@h@Ol@Bh@VXRPh@P`FDl@Jj@Zl@v@Tl@TX@')
  
    Trail.create!(trail_forks_id: 4229, name: 'Powderface Trail', description: 'Gravel Access Road
  https://kananaskistrails.com/powderface-road/2016/', length: '31597.2', difficulty: 7, coded_path: 'mqlvHf|d|TbCdJ^pNFpNg@rZCpNdBtEpBrDlApQtEvI~CfCdEfBpJx@bLhGhJtHx@vIeAbL~@|HLzHd@zDXfFTxQ`BjHjCzDtAlH`BvFRzOr@bG~DdBvCzKrDnKrCbCpBn@`CfF|IxErI~MxIh@hI?nDjEfBnHtGrEhAjCpBpCnBVtAlAbFbOtBrOjBxGjBdLxIvJ`DGvCtDtAh@hAGvLsCtCr@xHgFtLlApEwE|DcAvFxFrEqB`DpBdDmAbDrAnBtDvBp@jBI`GqD~GmBpGiCfCpGxHa@dOxJlDuA`OqJzOeQlFwB`ElBrImEpIaFnEyDnJsSlC{DvFiC`B}ApDuAfDa@hDF|M_JfCgMB{Kp@cElDmEdC}DhJgIvBsApCwFzDuErEuAzCdBdA`@fCcArRiKfEaGpBaKfFcDlDg@jCqBdCoAfCUvA?tDw@nFe@xC}AbFoBrDf@jDy@bCuBrA{E`BfEvD`GzBlBxBj@fAFjCdFfBxJv@~@`AkAHqCx@wCg@eK`J}GvEcBfCg@jIaIzCyDn@iEp@mCtCaDzDeCrJyHpC_A|F{E`NiGnHJfH_ApEwArEgA|H{GrF_AbGoBdGkAjDyChGaObBeJdA{ChAqLrB{Lv@mFPgCXyAjBaBz@]lCu@vBiDxBoCzAY|EB|HjBxIxC`F~@tDMhLaB~DoFz@]lFXvJNhEOfCiAhKyGrCa@lDzBtA^jBAnF_@tQ_L`CcAdCg@jC}EnEa@nLRhCwAhB{ClAqCrBa@nD~@tHhCzCJ`CGdDyC|DeAxD_CtFIbEqBfH_HxAuDdCy@rOaGxM_LzDsDzKsF|@}@z@wDvEaFxE_BvF{KhF{DlFeExFqC`CmEPuCnCcEbCoGlBgDfDgA~BsBlNsQzGgIl@y@xAg@zAmAhGiLxD_Jb@cDxB{B`CcDn@gKlFwJjAiG')
  
    Trail.create!(trail_forks_id: 146167, name: 'Tom Snow', description: '', length: '21002', difficulty: 4, coded_path: '}plvHdvd|T{@qCq@aAi@e@i@qAScAIq@Lw@`@WVaA^aC^ANa@PQ?ONQHYNYX?PHFIFHr@QFQt@JV_@cAuF?Wa@yBQWQEG]a@WQc@a@a@GYa@]QY?u@Gk@GO?c@Iw@?aBHi@mAeE?a@Y}AuAqCOEQ]Q?GWOJQBYCY]a@QYWa@eAa@a@QGGk@YcAQa@OmAFs@Pa@?cAFa@Pk@Xa@FYGYF{@Fa@?{@Gs@?qCG{@Q]a@aBk@}AOYmAgBOa@k@a@GO}AgBoBoBIYOmBFc@j@cAFi@?k@Ga@?{@Qs@?YXqCXgF?WN_B?Wa@eAO{@?i@Xk@FY?uAGkAQqAQe@?QGa@Qi@Gc@OWIY?QHQI{@?a@OK?UICi@mC?e@FY?sDOqAIa@?k@P{@QcAOa@?a@Ga@NeAPi@?QNG?k@Pi@?]Gw@Qa@GmAIa@Hi@?mA`@eB?c@XiDFM?_AFk@?OXqAPaBXqAFmCFK?iAHOIQi@i@Ik@PeBFI?WHY?w@h@kBPY?i@Fk@?yCFe@?yAa@aGGe@?oGFa@?cAGe@?Ya@kBYi@YQQGmBCc@MOGs@w@QYq@oDQ]GyA?a@Qw@q@sFc@aCOe@a@uG{@aCYuAa@uCIkAOmAs@yCGg@?kAFk@FS?YFM?e@He@?k@I{@GY?kAFYPQFYz@gAPg@?WFc@XcA`@s@PK?M`@sA?YP]Fs@?UPi@Fg@?yAQi@Ha@bAa@Nk@Pa@F{@HQQi@P{@z@aC?WF]lA_DFa@dBoD~CsDd@sBPXNCXMX?FLHBN?FTXVPTFXXXPv@F?FMF?PLr@o@NGj@?`@a@F?XIPHN?PFFQXGj@FNGFGdAYX?XJh@f@PFNG`@N`@b@r@pBPDh@l@PUN?z@q@b@CXUV?HFFLPBp@C`@s@HYz@qANcA?YHCNo@`@i@HY`@a@FCnBJ`@PP?XNN?PPN?z@a@P?`@]FUhCCPBNTPBNs@?YHa@?qCFQYkA?MFSPE?SFCHMFL`@BPCFUPCNg@PWh@gBPK`@qANiA?e@Ps@FGlA?PTNMPLF?PMN?FGHFFLXMFGj@FNL|A?XMHL`@?XU`@TpC?NMb@?FLz@?NJP?PK`@JNLHBFRPDFRNXHBNXX?FHb@?VNPTXBFTPBNTP?r@\FRPBlBCzC\XGVUb@KlB?XMXWz@iAPa@XQVYP]XWXo@Xa@p@oBb@{@`@YNYXY`@oAXkBj@uAXa@NCPg@r@WFFXeANW`@EP?PSV?H]Fo@POFk@FO`@_@X_AX?PGXCN]j@Yz@uCNo@`@YdAwBz@cAX?p@iAb@S`@]N]P}BNSj@C`@g@j@YFO?QNqAPq@z@cBPONa@PE`@m@Pk@z@i@bAQbAkAj@CXUVCXJHP`@FjA?~Ae@X?rDqAXGtEoBXCh@qAX?FQXOj@a@Xs@VYXG`@YX?j@GXQp@Qb@]p@q@Po@?Q`@WFFP?`@QX?h@OPFXXNXdANXPbAC?]P?Va@b@Qp@iCHi@XQNOj@_A?YQ]i@Qs@Pa@QQa@?Gz@aAFWPUPa@h@k@bAOlAk@z@{@XKXUXGVQPYPOFQ`@i@?]FYdAmCFa@PYFY?a@GYIQ?YHi@`@a@XC`@U`@{@FGr@{CFa@HGFa@FMPSNEHWh@gD?M`@m@PCX]XeAFGXgA?o@Fa@z@qCPa@XuA?a@`@s@N?XG`@k@PGPYV{@?YPa@PQVs@PO`@aBP]Fk@?Qj@yCVmC?u@OmA?k@Qi@?a@GYQYOqA?Ks@NG?Q]YgAOa@_B{Ba@cB?YHi@IoB?a@X{@?GlAeANq@b@aAFe@z@mANGPO`@}@j@W`@ENDj@k@h@?z@XXGX?z@UXUPYh@Or@a@h@QXUXKr@?NGX?hCk@X?NPP?XRNKP]F]PYtAcA?a@FYr@eAbAOvBiAPw@h@WPQ|AYFGPa@`@c@Xi@PcANQ?Or@}@z@?`@b@`@N`@?j@OX?`@c@XO`@w@XUXGFYr@i@FQ?mArDmEXKPUXOV?z@NX?`@OPa@j@YVQb@mAbAeB`@?XYPGVa@PI`@e@PKp@eAPOPa@XYNI`@{@Xa@Fs@r@aDFa@?a@Hk@?sD`@wBh@k@r@a@lAoBXOFa@?YQa@?c@Ha@bA}AlAYh@?r@O`@Q`@Cz@o@XG`@Yj@i@h@rDj@xGVr@b@j@jA?r@`@tErD`@Jb@K~BgBlAWVQ`C?`D{@r@?pGr@`CmA`@sDr@wBIk@GuEYgFr@mGQoDHiGQiC?}Aa@aDGmCFgFz@iAXGlA{@p@O~AqCYwBuAgBQeEP{DpBiEjF{BdBTdAiAlAYvBqCxCoDb@Gh@a@hACVk@lA`@v@O`@a@d@Mz@~@L\J~APl@JXpAtAT`@XtAJF\Hn@FFn@PVRPdAPNJ`@r@P`@TfAFf@L`@@j@z@`@f@a@Zc@^U\KTYF]PYXBh@KX?zBe@XU\w@n@cCFc@Ta@BKh@UL?NQP{@?]\yAJYT?z@T`@BTCn@]\BVPXJb@YpAS')
  
    Trail.create!(trail_forks_id: 4224, name: 'Ridgeback 3', description: 'Ridgeback is one of the newer trails in Kananaskis and is maintained by the [L=http://www.cmbalink.com/]Calgary Mountain Bike Alliance[/L]. It"s a mix of machine-built and hand-built construction, designed to provide an alternative to the perpetual wetness of the [L=https://www.trailforks.com/trails/tom-snow/]Tom Snow[/L] trail. 
  
  Ridgeback and [L=https://www.trailforks.com/trails/tom-snow/]Tom Snow[/L] come together at three points, dividing both trails into four sections, all of which are good in either direction. The parts of [L=https://www.trailforks.com/trails/tom-snow/]Tom Snow[/L] that Ridgeback bypasses are almost always wet & muddy.
  
  [L=https://www.trailforks.com/trails/ridgeback-3/]Ridgeback 3[/L] is the longest and hilliest section of Ridgeback.  The middle part runs along the ridge which features some rocky sections.  The descent to the south features a number of bermed corners and a section of boardwalk.', length: '4108.04', difficulty: 4, coded_path: 'wovuHxjc{TMGOS_@CeBd@KHm@ZYXKR]`A]j@QLK~@YtAMPKTS^]vAK`AKb@o@lAo@zASZGTEn@i@v@ELE|@Bh@G^IPY\u@bBUDc@RcA|AWv@Ah@Kl@M`@MZOv@IP[NAH@jBBLJT`@d@@HANYVADNPHELBLABJCNEHADJ^Bj@Ij@U~@@LLXt@rATRVl@^b@HDCBYECDBNADC@SCMFDNXHd@@BFABc@HSVL\Kl@MNYNU^MFk@b@YL[HOJq@Xs@f@q@`@u@`@[Vo@Xk@b@YF]TM@w@Tk@h@a@Na@FONODOT[pACZJX?x@CZKZOT[VSJY\aAb@_@h@EFWHS^o@h@SBMLa@RU\EBy@\]FIAMMGAQ?_@GOFEAWaAUk@GIIGc@Ea@MCBG^OP[Pe@Rc@\YJQVa@FGCOYW@SCc@Pc@ZM@Qd@EFSDOVEB]?IBo@b@SDQL?J@HDFRNTx@AfAFX?JQv@_@t@GDs@h@a@PKLe@HIE[PI?KEE@IRCVGDK@ED@TZX@BZDHNLBr@p@LFF@PCXB`@Y\ITSb@I^a@f@_@HGPATUDHJnAEbADTCRHVFDV?HBNMJCPQBHCn@@R?l@Qj@k@d@M?[JQAQGc@W_@Ba@^k@dAMDCTGNM@UIUHQPO^?HT`A@BTDRPTf@j@`@NZLHLXLt@BfAI^Kv@Qb@KfAAfA')
  
    Trail.create!(trail_forks_id: 7028, name: 'Jumpingpound Ridge (South Trail)', description: 'The longest and most challenging climb for [L=https://www.trailforks.com/trails/jumping-pound-ridge-trail/]Jumping Pound Ridge Trail[/L]. Considered to be in poor condition since the 2013 floods, and it was pretty rough to start with. Loads of loose rock and root steps. Not too many hikers, but a few horses.', length: '5429.65', difficulty: 5, coded_path: '{jwuHd}k|TKmGlCgS`@uDpAmBP{@M{GYaEsB_Ai@cAs@kDYeB?qAGmAFuCHuAs@UUX]KFw@kAh@h@gAHmAFgJNi@a@iCq@?mATa@?YUcAn@mA?QUa@C{@w@uAYi@Qa@j@?bCVv@{@]i@s@yCcCeAi@YbAb@lEIv@i@U{@Ga@YgBQgCGmAGGIuAq@s@?YRmAYi@?s@r@i@?mAn@a@v@s@d@cAtAk@`@sAhAmA?{@BgBRa@L?lA}AVmA?q@r@k@KiG?{@\}AQs@s@oBr@a@d@?Xa@v@a@hAYXFd@a@d@Pf@k@jAa@bAQPa@X_C?qCtAa@Xk@Ri@f@YJeB?{@v@YFs@?k@Oq@?a@N}@Oq@?a@Qc@?i@PuA?a@QY`@QPGn@OVILa@`@i@bAk@j@i@fAa@\s@H}A?YMa@?k@\QPeB?a@\YBk@Ta@Xa@JYPa@`@YNwBfBi@XuAjAeAb@cAbAOXc@Rq@LmA?QJWYc@SWE')
  
    Trail.create!(trail_forks_id: 28834, name: 'Baldy Pass Climb', description: 'This is the easy way to get to the top of Baldy Pass. It"s a long climb along an old hiking trail / FSR that crosses through some cutblocks. Watch for signs, don"t get suckered into heading off toward Lusk Pass or it will be a very long ride indeed. The climb isn"t that bad until the last couple of km, where it gets steeper, looser and narrower. The weather at the top can be  several degrees cooler than at the bottom, so don"t be surprised if there"s snow off the side of the trail by early September.', length: '10494.4', difficulty: 1, coded_path: '_pmvHvoc}Tl@kEJMdAsJa@eBi@{@G_Em@m@iCeBo@yAT_CVkABkEqDuQcAsGkEqIFe@pBi@~A@xAa@tB`A~@YrEoB`EqA`@NpAdC|@fEP^b@?Vq@{@iO[sD?qDn@{Bf@oA`@IRPPr@j@bBfAt@bDbC^t@dA~Fp@nCpCtDlBnD|AE~BgBzB}@vDi@`@U`@{CFy@KmUV}AzD{HrCkJhAu@jA?hCp@pATt@V\\^xD@rBfAhIl@tAjBxA`@b@t@dDt@rBjBZfAcA`@iBj@sFZmAt@i@z@G~@j@b@x@|@R|@]`BsElBiIb@uCdAiDRiAHaBMoCg@eDc@}ADiAb@{@tCo@zEjBx@fCxA`A|@b@Hf@`AnAjBj@`@G~CyD|AoAnAk@`CYzBeAzBmAhBs@rCNpCzApA`CxGbBhGw@rDsAnEsClGi@~GiGxCUrC|Fa@pFq@rAkApAwAjEg@`AUdAu@~BKtAFj@THnEz@dE?nB`AtBbCp@EROdAvAbArBjAJ|BzHAhBMReDHa@LFhAVdBEz@OrAmAjBkApDJr@TNr@w@bBw@|@BlAOd@FPGL@@J{@tBy@v@KtD?z@D~A?~AK`Ae@bBMhAu@hAi@~BkAv@MCg@NGP_@PON[H]`@iAt@W`@')
  
    Trail.create!(trail_forks_id: 7996, name: 'Stoney Trail', description: 'This is a connector trail/road, and not worth doing on its own except for beginners.  Lots of hikers and horses on the weekends.
  
  [L=https://www.trailforks.com/trails/jewell-pass/]Jewell Pass[/L], [L=https://www.trailforks.com/trails/prairie-view/]Prairie View[/L] and the Camp Chief Hector DH can all use this trail to make loops.', length: '19578.6', difficulty: 3, coded_path: '_p{uHzow}Tc@KmHJmDEeFJsBGo@@k@Jg@\_@f@]bAQTc@\w@N}Es@e@OUUkAaBe@[MCaG?wDEsCLs@?s@Gi@KmCMe@BsDx@iCIMK_@cB}@_By@aAMQ[UsA[IIwA{AACgCsBcAsBIGk@Ma@]y@eA]]_@i@m@}BMYk@o@i@cAiAqAg@w@{B{B{B{Ai@i@WOoEo@s@SaACSC]OW_@w@OoAm@Oe@GYPwC@o@Ea@Uk@}BoDc@k@uAcC_AmAQm@qA_CiBgCg@{@[m@Sw@Uk@eAuBGIi@Q]g@cA}BWe@{@iA_DaF]k@oBqCiFoI?YRw@f@u@\SFKFy@Ks@EOa@W{Aa@[W[[}@yA_@a@oBYYD_@Je@Ra@IeAqB_F{Hq@gBg@k@[e@u@eBSUg@Mg@[wA{Bc@y@gAeCcCuGWy@w@}AcAiCeGmPMi@EeAGOGs@OO_@EKIcBoE[sAK[g@w@KUmDyIIOWY[MMAe@@_@G{@cA]g@c@oAS[QQ}@k@kAgAoCyB}EwEsAq@oAmA[m@{AgAwAqAs@e@q@s@oC}BuB{A_@[{@{@kA_A}BeAs@cA{@}@u@WSQWs@Q[mA{@s@o@a@q@iAaAQ[i@iBYc@y@mBUo@k@iCMaA_A{Bc@i@w@mBgBwBg@MwA{@g@OqCyBs@iAUu@_@SQFk@|@cAd@mBCc@DSAeBSi@Oa@S]c@_@aAOg@CcAWmB]w@YSKEe@BMDq@t@YASCq@LQAa@KmADa@Ee@Hg@EoBFy@Ee@?yB\cAG]UGAy@HiCH}HDu@EcBJi@A_@GO@a@Rc@L}@JgCFgGMyCBoAMm@BwCIs@c@qBEo@Bi@?{BNaJOcADiSc@{X]aBI[Kc@UYYQKs@{@mByCuB{Eu@gAc@WuAc@sCmAk@]kBwBs@kAa@q@a@mACOI_CEYgBiFc@qDSgAM[aAiAIYQwBG[{CsEq@m@mAaBsAiAc@YaGsCIKo@OWMg@_@[I_Ai@uCoAq@g@a@MmB_BgBuCYy@Wa@c@iAyKmTyAgBwCkCaA_CgAmDOq@iAcGGu@U{@Ow@O{Bq@sCAw@[u@uDwP[uBGkBmAqRk@cDqAiCiAmBiBuBIGqAmB]_@gAeAg@Ya@Oa@SkE}Dc@]_BgB[YsB_BkBsBg@_@g@OaAw@uBuCe@e@[M[A]F}DvAIAoCvAc@Jo@G{Au@OEm@Cs@Fu@VsA|@_Dt@GDCPQPmAn@wDrCs@|@sF~EcCnCWRoAfBsAx@aATg@DWVMBEAi@dAIDM@cBUQKIK[Ek@Lc@@KBs@`@}@ZwABy@I{@BWBk@CO@c@ZY\cA\K?mBKcA_@WXy@Am@SkAu@o@Wg@_@eAkAi@W[UMe@GgASw@c@sFsAcMCAaAlAcB`B}@t@eCpAo@RqAXsANc@JyIt@cATSd@IFaATy@d@cAjA{@hA{@`Bg@nA_@rA]zAw@rFE`APlB')
  
    Trail.create!(trail_forks_id: 29315, name: 'Access Road', description: '', length: '329.598', difficulty: 1, coded_path: 'o{ovHluk{TaDnFwDbA{@bAkBX')
  
    Trail.create!(trail_forks_id: 60335, name: 'Cochrane Ranch Trail', description: 'This a is a green cross-country trail with a few small blue points.  The route indicated on the map is only a suggestion.  The trail can be ridden any number of ways.  Ride it a few times and you will get it figured out.  A few laps on this trail is an excellent way to get some non-pavement exercise if you don"t want to drive all the way out to Bragg Creek.  On the weekends and after working hours this trail can get a lot of foot traffic on it.  In Cochrane pedestrian traffic gets the right of way so keep that in mind or you may get some dirty looks.', length: '5871.36', difficulty: 3, coded_path: 'kvnwH~pvyTIMk@c@@k@AIYYa@o@Oy@u@_BwAoAu@oAe@sAMQ]]g@W_@Mm@c@e@c@[a@Ui@OO]cAWyAFqAHa@Bo@XoADu@IcAJaAV_A\g@@KWmAIK[ESMm@Bu@M[BYCIGIa@IGKA[VIB_@q@Oq@CWOWEMWMIk@IQW]CI?m@AQKi@Cg@Ok@MuAE{@UyBLa@?KAkAEq@r@wBNMHCh@PF@FCFKH]?MGIIEiBOKGIOK_@Eg@EuBMkBIkCKgASgAa@uA[cB[iCa@iCy@{D_A{HQ}@o@iFKc@Og@e@eCe@kEc@oKCUKe@Ek@Os@Sq@i@cA}A_Cg@sAKoAQmEoAwHEq@D_DJeCHSXv@Hf@@PArAJvBBJ\l@Bb@JhAXTFNLzATlALdAVx@B\H^V\Dh@FHF@PRLnA\hANXVH@JFDEFHTRjBN^DR@TAz@Hv@Vp@j@t@DJ@LCVB`AVrCBb@Rl@V\Vf@VjAR^FRD|@Fd@VbALnA@TN~@HhAFZBd@NfADPLTBJJJXfBJbA@nAFrAFf@PpAZrAJ|@NVBLEj@Bz@Ff@@|@BNFjBEhCDRTb@\rABzAGxALv@L\NhAFz@Lz@?p@Hd@FdADP`@jAr@pAPzAf@xAv@fAVn@z@dAP\HXp@zAd@rAVdATjABp@`@jB\bAj@nAJNZTLNHVRJn@j@h@~@v@`A^Z\j@HDRCFBl@b@PH^XPf@\d@Bh@Jl@NlBDFFN^~A?KAD')
  
    Trail.create!(trail_forks_id: 8590, name: 'Rundle Riverside Trail', description: 'Masochists need only apply. Although not physically demanding, the trail does take it"s toll on the body via soul-crushing roots that cover the trail from beginning to end. There is some fun to be had on a few short downhill sections but you"d be hard pressed to find anyone who says these sections balance out the rooty grind otherwise.   
  
  Can be ridden either way - net uphill going eastbound with a short, tough climb at the finish as you get to the park boundary and Canmore Nordic Centre. Multiple sections regularly stay swampy well through spring and into early summer as the trail is completely shaded by Mt. Rundle.
  
  Usually combined with the [L=https://www.trailforks.com/trails/goat-creek/] Goat Creek[/L] trail to make a big loop (~50km) of Mt. Rundle. Otherwise, it"s good to ride once a year to remind you how smooth the other trails in the area are ;) (except [L=https://www.trailforks.com/trails/upper-stoney-squaw/] Upper Stoney Squaw[/L]).', length: '8440.78', difficulty: 4, coded_path: 'mmawHffp_UY`@WVq@hAIDiALyAZEHUSAEYmCGMSSIEs@UMA{@BMA}@H{@Z{@h@_AZi@EqALWFmAdAgAZqBtB{@h@QPOn@MTAHi@v@GNuBpAe@@g@b@sAr@s@j@c@XqA~A[TcAzAYTaBfCe@dBw@|BOZc@vBOzA?`@[dBOl@c@rDCFG~@Ot@E|@sAhJIbCo@tCmAbEm@dDo@dAcBhEy@fAuBxAg@REDuA\_@FoAf@cAJkDz@QHQRWfAgA|AqAn@}@V]Aa@O}AH[COUYUYIk@TYPo@PiAjAg@Vu@hA]z@cBlBs@h@s@fFMl@MTGTUlBc@~As@xAMb@Eh@o@xBKj@[Te@He@I_@Fc@Xa@^kBlBeBdEOv@}@v@[`@Ox@{Ar@IJOj@k@~@c@vAINeA`AaApBgCfDWd@UhCWb@OHYV_@l@Wp@e@vBBh@E\Ur@EBIj@KTyBvAm@x@O^QhB@~AK|B]bBaArCMn@KrAHf@q@|DANJd@BBJbB_@~B]x@Mp@]h@SREXq@rAu@rAY`@q@n@IPc@zAiApC[pAQb@YFMLE@UEQX}@`DEVDh@i@hAe@X{AbDg@|CK\_@hFj@hDh@pBAvBTtCH`@G`@K\B\e@`BM`Bm@bCC`ACNaArEIxAUtA?JN^?~@R|BCpALz@b@zAHb@Th@b@\Rv@TjBj@hAb@vABRY|@EFy@^iAfA_@XcAKwAl@i@\gAvBYt@i@z@I`@AVPv@@x@Ad@gAzFIj@Cz@FnAAFZhA`@z@`@vBJH?b@HTbAlA`@~AHxAItEYfBk@nFCjB@z@OfBS~@aAlCo@|@a@pB_A~CUfAi@rAYPMj@[vB')
  
    Trail.create!(trail_forks_id: 146127, name: 'Prospector', description: 'an amazing little path', length: '714.226', difficulty: 5, coded_path: 'qavvHrf}}T}AO_DxASNwClAuBjAg@PSLkA`A_@l@W~@Id@WzEIZe@f@i@ZYDQH{@`A{@lA')



User.create!(name: "Cristof")

Rating.create!(feedback: 3, trails_id: 1, users_id: 1)

Comment.create!(data: "Pretty nice could use some work", trails_id: 1, name: 'Thomas')
Comment.create!(data: "Pretty nice could use some work", trails_id: 2, name: 'Thomas')

TrailSolution.create!(description_to_fix: "SO MANY TREE'S", timeline_days: 10, cost: 250, collaboration: "myself", trails_id: 1, users_id: 1)
